### ISSUE TITLE
Super High CPU usage when using beatiful-lyrics

### ISSUE THREAD

**Issue by Nadipkuh** [surfbryce/beautiful-lyrics#514] opened 2024-05-16 09:58 UTC
**Before getting into problems or suggestions I just want to say thank you for updating this extension.**

ok.. so basically like in the title when i'm using beautiful lyrics spotify almost uses 50% cpu usage ( not optimize ).
![high cpu](https://github.com/surfbryce/beautiful-lyrics/assets/161140906/3a8bf8ea-d7ea-4d27-ab6f-7d84c8a09501)
but when im closing all the tabs it become 5~% cpu usage.
![low cpu](https://github.com/surfbryce/beautiful-lyrics/assets/161140906/fc68a60b-320d-4b06-ae6d-438251e6a943)
just a suggestion, maybe you can add a low usage mode to reduce CPU usage, make the visual choose one gradient color from the NPV image ( for the ambience ).

**Comment by surfbryce** [comment] 2024-05-16 10:00
Duplicate of many many issues before this one, it's been talked about to death already, there are plans to address this in a future update; nothing that can be done at the moment until then

**Closed by surfbryce** 2024-05-16 10:00 UTC
Labels: duplicate
