### ISSUE TITLE
Lyrics Missing and Reappearing

### ISSUE THREAD

**Issue by JDTHEPS** [surfbryce/beautiful-lyrics#323] opened 2024-03-17 21:18 UTC
**Description:**
I have encountered a bug with the beautiful-lyrics extension where certain parts of the lyrics are missing and then reappear later in the song.

**Steps to Reproduce:**
    - Enable the beautiful-lyrics extension in Spicetify.
    - Play [ทุกความทรงจำ](https://open.spotify.com/track/3iJNeAiZwFxiPHWk456Bcw?si=047b3d11db184ec8) by [Only Monday](https://open.spotify.com/artist/2zByTMDKM5g76Kbz4huf0A?si=z_3IEZZVSFWrdwTDAOAKPg).
    - Notice that certain lyrics are missing initially but then show up later in the song.

**Expected Behavior:**
I expected the lyrics to display correctly and consistently throughout the song when using the beautiful-lyrics extension.

**Actual Behavior:**
Certain parts of the lyrics are missing at first and then reappear later in the song, causing a disruption in the lyric display.

**Environment Details:**
    - Operating System: Windows 11
    - Spicetify Version: 2.34.1
    - Beautiful Lyrics Version: 3.3.1
    - Song: [ทุกความทรงจำ](https://open.spotify.com/track/3iJNeAiZwFxiPHWk456Bcw?si=047b3d11db184ec8)
    - Artist: [Only Monday](https://open.spotify.com/artist/2zByTMDKM5g76Kbz4huf0A?si=z_3IEZZVSFWrdwTDAOAKPg)

**Image**:
Provided image that some tone mark are missing or cut off when it hit that line of song
_Left side is before line, Right side is after line showing_

![Untitled-1](https://github.com/surfbryce/beautiful-lyrics/assets/151321308/ac07cc6c-b850-4454-99b9-97cc49b33dc9)

**Comment by surfbryce** [comment] 2024-03-18 00:29
Duplicate of #304

**Closed by surfbryce** 2024-03-18 00:29 UTC
Labels: duplicate
