### ISSUE TITLE
The list of artists collapses in on itself when it tries to scroll them.

### ISSUE THREAD

**Issue by marcusbandit** [surfbryce/beautiful-lyrics#563] opened 2024-05-18 12:22 UTC
https://github.com/surfbryce/beautiful-lyrics/assets/22052802/dcc30669-e8de-4e21-b451-3ef3e965233d

As can be seen in the video, the text seems to try to scroll to show all artists. But the speeds seem to be applied wrong somehow. So they just collapse in on them self. 
After a while, the scroll animation is played in reverse and the loop of collapsing and reappearing continues.
It is definitely not as important to fix as the many issues regarding missing lyrics. But it is funky enough to report.

**Comment by surfbryce** [comment] 2024-05-18 21:28
Duplicate of #515

**Closed by surfbryce** 2024-05-18 21:28 UTC
Labels: duplicate
