### ISSUE TITLE
No synced lyrics on other device

### ISSUE THREAD

**Issue by legendsuperstar** [surfbryce/beautiful-lyrics#557] opened 2024-05-17 23:40 UTC
I have another computer to look at the lyrics while its playing on my main computer, the lyrics aren't synced if its not playing on that computer. I want the lyrics to be synced on my other computer while the audio is playing on my main computer. It was working fine until the newest update.

**Comment by surfbryce** [comment] 2024-05-18 21:22
Duplicate of #531

**Closed by surfbryce** 2024-05-18 21:22 UTC
Labels: duplicate
