### ISSUE TITLE
Theme Sleek Issues

### ISSUE THREAD

**Issue by GoldXeno07** [surfbryce/beautiful-lyrics#368] opened 2024-04-08 02:38 UTC
![Screenshot 2024-04-07 223307](https://github.com/surfbryce/beautiful-lyrics/assets/70493359/bc39f75e-1689-422c-99db-33ae82f8f92c) It just shows a blank screen when you press expand but works when its mini.

**Comment by surfbryce** [comment] 2024-04-08 02:44
Duplicate of #340

**Closed by surfbryce** 2024-04-08 02:44 UTC
Labels: duplicate
