### ISSUE TITLE
Stopped working when spotify updated himself (last time working was on 3rd april 2024)

### ISSUE THREAD

**Issue by antoniovelcu** [surfbryce/beautiful-lyrics#346] opened 2024-04-04 18:14 UTC
Hi i recently installed spicetify (around 2 weeks ago) and i decided to use Adblock by CharlieS1103, Beautiful Lyrics, Quick Queue by ohitstorm and the theme Default Dynamic by JulienMaille. Unfortunately today i opened spotify and realized the Beautiful Lyrics wouldn't show up, even if the button to enable them was there, if i pressed it i would see a black screen where the lyrics should be. Weird but the lyrics in the  right sidebar would still work. Please im desperate i want my lyrics back.
![Screenshot 2024-04-04 194857](https://github.com/surfbryce/beautiful-lyrics/assets/166056429/4645f38d-767a-4774-b42d-761412ee3b3c)

**Comment by surfbryce** [comment] 2024-04-04 18:43
Duplicate of #340

**Closed by surfbryce** 2024-04-04 18:43 UTC
Labels: duplicate
