### ISSUE TITLE
Theme SpotifyNoPremium Issues

### ISSUE THREAD

**Issue by AngryAutist** [surfbryce/beautiful-lyrics#491] opened 2024-05-14 05:31 UTC
When i click on the lyrics page, it just comes up blank
![Screenshot_6](https://github.com/surfbryce/beautiful-lyrics/assets/131738654/4dc0789b-dc62-4692-acc6-67cc646cd554)

**Comment by surfbryce** [comment] 2024-05-14 05:33
Duplicate of #441

**Closed by surfbryce** 2024-05-14 05:33 UTC
Labels: duplicate
