### ISSUE TITLE
The lyrics are not showing on the fullscreen

### ISSUE THREAD

**Issue by Meowtherronldo** [surfbryce/beautiful-lyrics#401] opened 2024-04-15 17:54 UTC
So this problem started a couple days ago when i was trying trying to see the lyrics on the fullscreen but all i see was a blannk screen the lyrics are working fine on the small screen but when i tries to fullscreen it it shows nothing. please fix this issue asap. thankss
![Screenshot 2024-04-15 232425](https://github.com/surfbryce/beautiful-lyrics/assets/129516177/88d7c84c-cb43-4f3e-be2a-8b7fb3684055)

**Comment by MrGenia** [comment] 2024-04-15 19:15
I can confirm the issue persists for me too

**Comment by surfbryce** [comment] 2024-04-15 19:32
Duplicate of #340

**Closed by surfbryce** 2024-04-15 19:32 UTC
Labels: duplicate
