### ISSUE TITLE
 The extension does not load and the "Now playing view" option is bug

### ISSUE THREAD

**Issue by th3alexdev** [surfbryce/beautiful-lyrics#641] opened 2024-05-27 08:14 UTC
I am from Venezuela

**Version**
Spotify for Windows (64 bit) 1.2.26.1187.g36b715a1
Spicetify v2.36.11
Theme: marketplace

**Developer Tools Files**
[Spotify.html.txt](https://github.com/surfbryce/beautiful-lyrics/files/15452785/Spotify.html.txt)
[Spotify.css.txt](https://github.com/surfbryce/beautiful-lyrics/files/15452786/Spotify.css.txt)

**Screenshots of bug occuring**
![Screenshot_34](https://github.com/surfbryce/beautiful-lyrics/assets/55007470/3ac87e11-b339-4ff5-9f68-b511b199de77)

**Video of bug occuring**
https://github.com/surfbryce/beautiful-lyrics/assets/55007470/aef6850b-13fb-4466-b7a2-f5be8731dad2

**Screenshot of Console**
Top half of console:
![Screenshot_35](https://github.com/surfbryce/beautiful-lyrics/assets/55007470/84eccc14-2ef1-437d-a80f-4412ae113768)

Bottom half of console:
![Screenshot_36](https://github.com/surfbryce/beautiful-lyrics/assets/55007470/a33e25e2-209f-4bfa-97d8-1472b02fa46c)

**Comment by surfbryce** [comment] 2024-05-27 17:15
@th3alexdev This is a duplicate of #609

**Closed by surfbryce** 2024-05-27 17:15 UTC
Labels: Duplicate
