### ISSUE TITLE
It doesent work

### ISSUE THREAD

**Issue by kalichT** [surfbryce/beautiful-lyrics#434] opened 2024-04-25 21:46 UTC
I need help with my lyrics it does not work when I click on it it stays blank
![obrázek_2024-04-25_234644826](https://github.com/surfbryce/beautiful-lyrics/assets/96803579/787db0ef-c892-4b3f-8051-e7c0991f9f1f)

**Comment by kalichT** [comment] 2024-04-25 21:47
I feel like ive tried everything

**Comment by surfbryce** [comment] 2024-04-25 22:21
Duplicate of #340

**Closed by surfbryce** 2024-04-25 22:21 UTC
Labels: duplicate
