### ISSUE TITLE
Edge and glow from text in full screen mode

### ISSUE THREAD

**Issue by Blankk02** [surfbryce/beautiful-lyrics#113] opened 2023-08-14 00:37 UTC
Hi, I would like to say that in the song where the text goes in blocks using full screen mode on the left side you can see that the lighting of the text reaches the edges.
You can see it in the screenshot below:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/01299a0d-0774-4226-9274-b428f5b188b3)

**Comment by surfbryce** [comment] 2023-08-20 01:58
Duplicate of #100

**Closed by surfbryce** 2023-08-20 01:58 UTC
Labels: duplicate
