### ISSUE TITLE
The lyrics don't load and stay on a screen with nothing showing

### ISSUE THREAD

**Issue by LeginioS** [surfbryce/beautiful-lyrics#376] opened 2024-04-09 22:51 UTC
Without forgetting that Spicetify and Spotify are up to date.
This is the error:

![Captura de Tela (14)](https://github.com/surfbryce/beautiful-lyrics/assets/98649381/24ad8ca5-b267-41cb-9bff-a0ec865ffc9b)

**Comment by fastnlight0** [comment] 2024-04-09 22:53
Duplicate of #340

**Comment by surfbryce** [comment] 2024-04-09 23:41
Duplicate of #340

**Closed by surfbryce** 2024-04-09 23:41 UTC
Labels: duplicate

**Comment by LeginioS** [comment] 2024-04-28 12:21
> Duplicate of #340

Do you already have a solution for this problem?
