### ISSUE TITLE
Add an option to disable dynamic background

### ISSUE THREAD

**Issue by aurelbdx** [surfbryce/beautiful-lyrics#742] opened 2024-06-20 01:39 UTC
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

Hi, 
can you add an option to disable dynamic background, I prefer to keep the Bloom theme colors.

Thanks

### What is your Suggestion?

add an option

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment] 2024-06-21 17:25
@aurelbdx Duplicate of #157

**Closed by surfbryce** 2024-06-21 17:25 UTC
Labels: Duplicate, Suggestion
