### ISSUE TITLE
Lyrics Issue

### ISSUE THREAD

**Issue by SuyashHere** [surfbryce/beautiful-lyrics#496] opened 2024-05-15 15:02 UTC
Unable to see the lyrics while playing the song.
![Uploading Screenshot 2024-05-15 203117.png…]()

**Comment by sabzeruz** [comment] 2024-05-15 16:18
yes this happen to me too

**Comment by boochySans** [comment] 2024-05-15 16:22
Duplicate of #441

**Comment by surfbryce** [comment] 2024-05-15 16:24
Duplicate of #441

**Closed by surfbryce** 2024-05-15 16:24 UTC
Labels: duplicate
