### ISSUE TITLE
lyrics not appearing in "now playing view" 

### ISSUE THREAD

**Issue by BtrayZ** [surfbryce/beautiful-lyrics#102] opened 2023-08-06 12:26 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/115880597/0c4775e3-c520-4b77-8af4-5517d1a77dcb)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/115880597/6e37da78-f3b6-4c9a-b9de-a94beb5cd434)

the lyrics appear on main lyrics page but not on the side bar in now playing view

**Comment by surfbryce** [comment] 2023-08-06 20:01
This is a duplicate of #89

**Closed by surfbryce** 2023-08-06 20:01 UTC
