### ISSUE TITLE
Still blank even after plugin update (19.4) and fullscreen not working at all (PLEASE FIX!!)

### ISSUE THREAD

**Issue by leinadd26** [surfbryce/beautiful-lyrics#412] opened 2024-04-19 15:49 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/167555267/a94d2f0e-438b-4629-bf42-166aedbb6504)

**Comment by aduckwithakeyboard** [comment] 2024-04-19 16:08
I got the same problem too

**Comment by Kirbytronic** [comment] 2024-04-19 16:54
me too

**Comment by surfbryce** [comment] 2024-04-19 18:31
Duplicate of #340

**Closed by surfbryce** 2024-04-19 18:31 UTC
Labels: duplicate
