### ISSUE TITLE
Bugged Lyrics

### ISSUE THREAD

**Issue by stratos1-ctrl** [surfbryce/beautiful-lyrics#89] opened 2023-08-04 15:39 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/130912076/a087532c-f685-439d-be25-691ba512361d)

Can anyone help me fix this?

**Comment by Gamesnic** [comment] 2023-08-04 17:02
Same for me, it's just broken and not animated

**Comment by surfbryce** [comment] 2023-08-04 19:30
@stratos1-ctrl What operating-system are you on and what theme are using?

Can you also screenshot the spotify/spicetify version you are using.

If you are windows you can do this by click the three dots in the top left and going to "About Spotify". If you are on MacOS just go to the top left, click Spotify, and "About Spotify".

Also @Gamesnic if you could do the same that'd be great

**Comment by stratos1-ctrl** [comment] 2023-08-04 23:51
![image](https://github.com/surfbryce/beautiful-lyrics/assets/130912076/be8e837e-c9b0-4576-8de3-81ea52fb26f9)

and I use this theme 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/130912076/434a6524-88fa-4a58-ac43-467164cb95fb)

**Comment by surfbryce** [comment] 2023-08-05 04:17
@stratos1-ctrl It's not a theme issue since it looks fine on my end;
<img width="458" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/ff2f8690-6efc-4324-8706-f2fb49110cd2">

Can you try reinstalling Spotify from the Spotify website and see if that fixes it? That usually is the problem is a bad Spotify installation.

@Gamesnic can you try this as well.

**Comment by aamyush** [comment] 2023-08-05 05:20
i am having thee exact same problem did you find a fix yet?

**Comment by Hexelont** [comment] 2023-08-05 07:57
![image](https://github.com/surfbryce/beautiful-lyrics/assets/90501238/99c390c4-c5eb-425b-ab80-284e9a96dd19)
i am also having the same problem. i have reinstalled spotify.

**Comment by Gamesnic** [comment] 2023-08-05 11:15
@surfbryce I didn't reinstall, only updated. Works now again though
![image](https://github.com/surfbryce/beautiful-lyrics/assets/49643487/ccafd851-3f2d-4958-b765-eae678db2193)

**Comment by stratos1-ctrl** [comment] 2023-08-05 15:28
@surfbryce a clean install or just a simple uninstall and install?

**Comment by aamyush** [comment] 2023-08-05 15:43
> @surfbryce a clean install or just a simple uninstall and install?
> 
> to add it seems when i click the full lyrics it works fine, its just the side panel. ![image](https://user-images.githubusercontent.com/130912076/258593958-e50da23d-fed0-4867-a19f-c4cd33bb4bfd.png)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/107539318/146c3914-02fd-4984-b7a5-c928c2a2802a)
same here

**Comment by surfbryce** [comment] 2023-08-06 09:29
Alright so a ton of duplicate stuff I just closed. I think I just realized what the main issue is for everyone here. I noticed that this issue was originally made 2 days ago. 2 days ago I made some changes that fixed an internal change Spotify made. What I just realized though is that the internal change may not have been made for everyone.

So the stuff I look for is no longer the same for everyone and is split between a bunch of people. Meaning some people get it to work and others do not.

I'm currently working on #51 right now and should have that finished today (August 6th). After I finish that I can then make the fix for this and push out the update right after that. I would push it out now if I hadn't already started updating the codebase and working on #51.

So you'll either see a fix for this released later today or tomorrow.

Sorry for the wait and issues everyone. Most of the time Spotify is the culprit for some weird stuff they do.

**Comment by aamyush** [comment] 2023-08-06 11:39
@surfbryce I think I speak for everyone when I say trust me its completely okay, take your time! Also do you have a patreon by any chance?

**Comment by surfbryce** [comment] 2023-08-06 20:03
@aamyush I do not have a patreon but I appreciate the sentiment.

I make enough money as is so I don’t want to take any from anybody, I do this so that everyone else can have a better lyrics experience on Spotify.

Thanks!

**Comment by surfbryce** [comment] 2023-08-07 06:28
@Gamesnic @Hexelont @aamyush @stratos1-ctrl Alright I just pushed out an update that should fix this for the side-bar. It would be awesome if you could restart/reload Spotify and the extension should be updated to 3.1.11.

I've made a change for it since it actually started happening for me as well because they changed something that finally got to me. I've also decided to put this update before #51 just so we can get this out of the way.

Please let me know when you can IF this update fixed it for you guys!

**Comment by aamyush** [comment] 2023-08-07 12:34
@surfbryce yes its fixed now!

**Closed** 2023-08-07 19:25 UTC
Labels: question

**Comment by stratos1-ctrl** [comment] 2023-08-10 02:13
@surfbryce thanks! it works now
