### ISSUE TITLE
adding beautiful lyrics extension crashes my spotify home page

### ISSUE THREAD

**Issue by TSULAV** [surfbryce/beautiful-lyrics#602] opened 2024-05-21 16:59 UTC
whenever i download beautiful  lyrics  extension and apply it it kinda crashes my spotify home page and it goes blank ....tho and   even after clicking on  lyrics button its blank ...please help
![Screenshot 2024-05-21 224042](https://github.com/surfbryce/beautiful-lyrics/assets/170453201/b7983b3e-d6f3-4579-8399-25f1c64d6e19)

**Comment by surfbryce** [comment] 2024-05-21 19:34
Duplicate of #502

**Closed by surfbryce** 2024-05-21 19:34 UTC
Labels: Duplicate
