### ISSUE TITLE
Theme SLEEK Issues

### ISSUE THREAD

**Issue by Kazestar** [surfbryce/beautiful-lyrics#423] opened 2024-04-23 19:57 UTC
![image_2024-04-24_025657451](https://github.com/surfbryce/beautiful-lyrics/assets/99455654/ea31adc6-e752-45b2-abd7-855717f669b0)

the lyrics page not showing up

**Comment by surfbryce** [comment] 2024-04-23 20:33
Duplicate of #340

**Closed by surfbryce** 2024-04-23 20:33 UTC
Labels: duplicate

**Comment by Kazestar** [comment] 2024-04-24 12:14
is it already fix?
