### ISSUE TITLE
No page content with right sidebar opened

### ISSUE THREAD

**Issue by petrostotskas** [surfbryce/beautiful-lyrics#575] opened 2024-05-19 16:37 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/154595553/16fd956c-e3d2-434f-946b-9bdcffda8578)

Closing the sidebar shows everything as expected.
These are my extensions:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/154595553/22134477-9f3e-48af-aa36-dd3d6fccc531)

Wouldn't expect them to affect this behavior tho..

Also I don't have no lyrics card on the sidebar, should probably make another issue for this?

**Comment by surfbryce** [comment] 2024-05-19 23:10
Duplicate of #502, but I will be closing that one so that people follow this: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version

So if you want to be the one to recreate go ahead, but follow those instructions, thanks

**Closed by surfbryce** 2024-05-19 23:10 UTC
Labels: duplicate
