### ISSUE TITLE
Can't acces anything, only see the moving blurred background

### ISSUE THREAD

**Issue by LayerCZ** [surfbryce/beautiful-lyrics#553] opened 2024-05-17 20:39 UTC
After installing the plugin, no matter what i do or what i click on i only see the blurred moving background thingy. Makes it impossible to use the app. Tried reinstalling everything bunch of times
![image](https://github.com/surfbryce/beautiful-lyrics/assets/70105041/4ede5c1c-fec2-4ede-ab90-ca38d1773806)

**Comment by garryspins** [comment] 2024-05-18 00:46
Duplicate #541

**Comment by surfbryce** [comment] 2024-05-18 21:30
Duplicate of #541

**Closed by surfbryce** 2024-05-18 21:30 UTC
Labels: duplicate
