### ISSUE TITLE
Lyrics: Error

### ISSUE THREAD

**Issue by JCTasaTech** [surfbryce/beautiful-lyrics#369] opened 2024-04-08 03:14 UTC
I have been trying to re-installing the Beautiful Lyrics, and i click the shiny mic, and there's nothing in the middle lyrics.
Official Spotify Lyrics Works, Please fix the issue.

**Comment by surfbryce** [comment] 2024-04-08 03:37
Duplicate of #340

**Closed by surfbryce** 2024-04-08 03:37 UTC
Labels: duplicate
