### ISSUE TITLE
lyrics are flat out, not working

### ISSUE THREAD

**Issue by sadhikamram** [surfbryce/beautiful-lyrics#374] opened 2024-04-09 15:57 UTC
I was trying to listen to a song and when i click on the lyrics, its just a blank screen? 
Its not on just one song its on every song! In certain songs, in the "Now playing view" screen, it shows the lyrics.
When I click on enlarge, it again shows the blank blurred screen.
Please help me with this...
![Screenshot 2024-04-09 212702](https://github.com/surfbryce/beautiful-lyrics/assets/166534970/9054c24c-0ac5-4231-9816-6f2eaca479b4)
![Screenshot 2024-04-09 132215](https://github.com/surfbryce/beautiful-lyrics/assets/166534970/ca876011-8921-4698-aeac-db7b80c28d41)

**Comment by Vivian-Adriana** [comment] 2024-04-09 16:05
its been reported already..
https://github.com/surfbryce/beautiful-lyrics/issues/340

**Comment by surfbryce** [comment] 2024-04-09 16:30
Duplicate of #340

**Closed by surfbryce** 2024-04-09 16:30 UTC
Labels: duplicate
