### ISSUE TITLE
now playing view change ?

### ISSUE THREAD

**Issue by EditKey** [surfbryce/beautiful-lyrics#492] opened 2024-05-14 13:37 UTC
Currently playing How can I change its appearance? It used to have the colors of the album cover, but now it's the same as before.
![resim_2024-05-14_163643565](https://github.com/surfbryce/beautiful-lyrics/assets/168360083/468d2167-aae4-4133-9f1a-a21753b39ba5)
like this right now
![image](https://github.com/surfbryce/beautiful-lyrics/assets/168360083/7b663743-cf2b-4901-b394-899111c2f38e)
and I want it to be like this

**Comment by surfbryce** [comment] 2024-05-14 18:47
Duplicate of #441

**Closed by surfbryce** 2024-05-14 18:47 UTC
Labels: duplicate
