### ISSUE TITLE
my liked song button seems placed wrong 

### ISSUE THREAD

**Issue by aduckwithakeyboard** [surfbryce/beautiful-lyrics#419] opened 2024-04-23 09:31 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/137604597/31535874-53d9-4b0b-b899-828e115f4761)

**Comment by Truysssss** [comment] 2024-04-23 13:02
sao hiện được hay vậy mình vẫn bị lỗi
![Screenshot 2024-04-23 200209](https://github.com/surfbryce/beautiful-lyrics/assets/140448046/a58aa44b-70af-42ef-8235-6201033fcc2c)

**Comment by IIcydi** [comment] 2024-04-23 14:17
> sao hiện được hay vậy mình vẫn bị lỗi ![Screenshot 2024-04-23 200209](https://private-user-images.githubusercontent.com/140448046/324843031-a58aa44b-70af-42ef-8235-6201033fcc2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODIxNDYsIm5iZiI6MTcxMzg4MTg0NiwicGF0aCI6Ii8xNDA0NDgwNDYvMzI0ODQzMDMxLWE1OGFhNDRiLTcwYWYtNDJlZi04MjM1LTYyMDEwMzNmY2MyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxNDE3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjlmYTkxMTkzNjY3MTYxMTI1MWI3YmEzYTYyZmQxOWQ2MjY4NjdmZWI2MjdhY2ZmNzk0MzQyMjMyM2E2NDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-uhbINo18DjtTgSFUAo5uEeWluHh2Wn0G3mYhPRplg)

tui cung y chang

**Comment by aduckwithakeyboard** [comment] 2024-04-23 16:58
các b down về bản 1.31 ấy với tắt update nữa
![image](https://github.com/surfbryce/beautiful-lyrics/assets/137604597/622bb385-1ef5-44e1-a466-3b7cb49862f3)

**Comment by IIcydi** [comment] 2024-04-23 17:20
> các b down về bản 1.31 ấy với tắt update nữa ![image](https://private-user-images.githubusercontent.com/137604597/324925070-622bb385-1ef5-44e1-a466-3b7cb49862f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTMwNTcsIm5iZiI6MTcxMzg5Mjc1NywicGF0aCI6Ii8xMzc2MDQ1OTcvMzI0OTI1MDcwLTYyMmJiMzg1LTFlZjUtNDRlMS1hNDY2LTNiN2NiNDk4NjJmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxNzE5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGUzN2Y2ZmI0NjkxOGFmNTIyNmU3YTQyMzBlMzU2Y2VjZDlkZGE1NjU3MWY3NTk5ZmFkM2NkMjAwODQ0ZDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OEvKPbGrTeSZQIXXmifOc5r3IqqAab7E-mrAwf9eHlc)

lam nhu nao ay chi tui voi
tui co discord ong tien vao kh

**Comment by surfbryce** [comment] 2024-04-23 18:46
Duplicate of #244

**Closed by surfbryce** 2024-04-23 18:46 UTC
Labels: duplicate
