### ISSUE TITLE
Beautiful does not show up and can't enter fullscreen mod

### ISSUE THREAD

**Issue by kmskara** [surfbryce/beautiful-lyrics#361] opened 2024-04-06 21:41 UTC
![image_2024-04-06_233527475](https://github.com/surfbryce/beautiful-lyrics/assets/166257818/a97398f7-cc1b-4a9f-8b1b-3436da6358b0)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/166257818/f1d5a707-d428-48ee-9f06-9d8a53acdfca)
I've been grappling with these issues for the past two days. Despite repeated attempts to uninstall Spotify and execute commands for installing Spicetify, I'm still encountering problems. It all started when I accidentally clicked a button that switched the lyrics to windowed mode. Now, I can't seem to revert it back to the normal mode.

**Comment by DerHK** [comment] 2024-04-06 22:07
The author has to update the extention. Just wait it will get updated eventually.

**Comment by surfbryce** [comment] 2024-04-06 23:23
Duplicate of #340

**Closed by surfbryce** 2024-04-06 23:23 UTC
Labels: duplicate
