### ISSUE TITLE
Add the option to disable spinning background for better performance. 

### ISSUE THREAD

**Issue by JimDude7404** [surfbryce/beautiful-lyrics#785] opened 2024-07-15 16:03 UTC
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

The current background code is incredibly intensive to run, and drains battery very quickly per se on mobile devices, and also can make them feel sluggish in some cases. 

### What is your Suggestion?

add the option to disable the background blur and artisit album spinning in the background, and just make it a solid color. 

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by Marmur2020** [comment] 2024-07-18 12:10
If you want to change the font you need to change the css code.

Here is the code: `.BeautifulLyricsBackground-Container .Front {animation: none;}.BeautifulLyricsBackground-Container .Back {animation: none;}.BeautifulLyricsBackground-Container .BackCenter {animation: none;}`

How do I disable?
Go to Marketplace -> Installed and find your Snippet and delete

How do I edit saved Snippet?
Go to Marketplace -> Installed and find your Snippet

How do I run code?
![image](https://github.com/user-attachments/assets/521aded5-23dd-42c6-a361-13df0c3b8814)
Paste the code in Custom CSS(I gave you at the top) and give Snippet Name to save it.

**Comment by surfbryce** [comment] 2024-07-27 16:22
@JimDude7404 Duplicate of #166

**Closed by surfbryce** 2024-07-27 16:22 UTC
Labels: Duplicate, Suggestion
