### ISSUE TITLE
Comfy- Themes_Beta) Beautiful Lyrics Not Showing

### ISSUE THREAD

**Issue by aesquivel16** [surfbryce/beautiful-lyrics#281] opened 2024-02-14 22:09 UTC
Hello, I am using theme Comfy-Themes_Beta and Beautiful Lyrics by SoCalifornian and it does not show. Here are where the lyrics should be showing but dont. 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/45436771/8a218c34-485f-40c9-a9f6-e75d1e79c914)

**Comment by surfbryce** [comment] 2024-02-16 12:17
Duplicate of #240

**Closed by surfbryce** 2024-02-16 12:17 UTC
Labels: duplicate
