### ISSUE TITLE
Artist name overlapping

### ISSUE THREAD

**Issue by ayushmath07** [surfbryce/beautiful-lyrics#543] opened 2024-05-17 07:23 UTC
Dk how to explain but ig this video would do that job

https://github.com/surfbryce/beautiful-lyrics/assets/65216063/b7da4d78-38fe-43e3-b2db-fcdb97b2690c

And not the only song happening to, ig it affects all songs that contain multiple artists
![image](https://github.com/surfbryce/beautiful-lyrics/assets/65216063/1394da03-46f9-4dc8-9104-ac2940f52d00)

**Comment by surfbryce** [comment] 2024-05-17 07:24
Duplicate of #515

**Closed by surfbryce** 2024-05-17 07:24 UTC
Labels: duplicate
