### ISSUE TITLE
Only display the current and future lyrics when playing

### ISSUE THREAD

**Issue by PIndividual** [surfbryce/beautiful-lyrics#803] opened 2024-07-26 07:10 UTC
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

When there are too many lyrics on screen, the one on the top always appears been clipped. On the other hand, when people are following the lyrics, they only focus on the current line and the ones after that. So the ones that already been played won't being paying much attention. 
![image](https://github.com/user-attachments/assets/27aa6f34-95a6-4e3c-bd81-f8b0cf7b5da8)

### What is your Suggestion?

Hide lyrics lines that has already been played, or only keeping one previous line visible. Only display all lines when the user is manually scrolling through the lyrics.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment] 2024-07-27 16:20
@PIndividual Duplicate of #606

**Closed by surfbryce** 2024-07-27 16:20 UTC
Labels: Duplicate, Suggestion
