### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Snoopy014** [surfbryce/beautiful-lyrics#697] opened 2024-06-04 21:15 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

So when i open my lyrics tab my cpu usage increases and is almost 40-60% pls help

and great extension btw 
:)

### What Country are you from?

Pakistan

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.38.720.ga4a70a0e
Spotify Runtime: cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Spicetify Version: 2.36.12
Spicetify Theme: marketplace
Spicetify Extensions: [beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

![Screenshot 2024-06-05 021407](https://github.com/surfbryce/beautiful-lyrics/assets/171742253/60d25254-4bc7-4746-bc11-89dc9dca9af8)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment] 2024-06-04 22:06
@Snoopy014 Duplicate of #185

**Closed by surfbryce** 2024-06-04 22:06 UTC
Labels: Extension Bug, Duplicate
