### ISSUE TITLE
cant open the lyrics page

### ISSUE THREAD

**Issue by jns2009** [surfbryce/beautiful-lyrics#479] opened 2024-05-09 10:31 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/169355443/c055dfca-a6d4-450b-b944-3c9a6ab4ca61)

**Comment by boochySans** [comment] 2024-05-09 10:34
#441

**Comment by Joeeeeb5** [comment] 2024-05-09 10:37
bro

**Comment by surfbryce** [comment] 2024-05-09 16:34
Duplicate of #441

**Closed by surfbryce** 2024-05-09 16:34 UTC
Labels: duplicate
