### ISSUE TITLE
The lyrics doesnt show

### ISSUE THREAD

**Issue by B-5-5** [surfbryce/beautiful-lyrics#437] opened 2024-04-26 06:21 UTC
![Screenshot 2024-04-26 092026](https://github.com/surfbryce/beautiful-lyrics/assets/79602422/47335af1-a37d-4f9a-85ef-07e1546bdf1b)

**Comment by surfbryce** [comment] 2024-04-26 07:58
Duplicate of #340

**Closed by surfbryce** 2024-04-26 07:58 UTC
Labels: duplicate
