### ISSUE TITLE
(HTTP 403) isnt it like blocked access? There was this issue on the lyrics becoming blank then tried reinstalling other version then this.

### ISSUE THREAD

**Issue by AbiWasabii** [surfbryce/beautiful-lyrics#389] opened 2024-04-12 23:39 UTC
![image_2024-04-13_073812732](https://github.com/surfbryce/beautiful-lyrics/assets/166880082/57846dc5-bcac-482d-b025-1babad19228b)

**Comment by surfbryce** [comment] 2024-04-12 23:59
Actual issue is a duplicate of #340, the error you (@AbiWasabii) experienced is not related to Beautiful Lyrics but actually comes from Spicetify Marketplace

**Closed by surfbryce** 2024-04-12 23:59 UTC
Labels: invalid
