### ISSUE TITLE
Theme comfy Issues

### ISSUE THREAD

**Issue by b0neth** [surfbryce/beautiful-lyrics#462] opened 2024-05-04 03:57 UTC
When I lyrics pag with the beautiful lyrics its just a blank screen
![image](https://github.com/surfbryce/beautiful-lyrics/assets/124420482/d8eaba13-d22c-4c6e-91dd-f0f6074812b1)

**Comment by surfbryce** [comment] 2024-05-04 03:59
Duplicate of #441

**Closed by surfbryce** 2024-05-04 03:59 UTC
Labels: duplicate

**Comment by b0neth** [comment] 2024-05-04 04:04
> Duplicate of #441

ty!
