### ISSUE TITLE
Full screen mode has an add to playlist button in the wrong spot

### ISSUE THREAD

**Issue by Ankpudding** [surfbryce/beautiful-lyrics#300] opened 2024-02-24 06:21 UTC
![Screenshot 2024-02-24 071950](https://github.com/surfbryce/beautiful-lyrics/assets/132187539/5f8d8bd8-f0e8-4c9b-89a5-7097a07c1041)

**Comment by surfbryce** [comment] 2024-02-24 07:15
Duplicate of #244

**Closed by surfbryce** 2024-02-24 07:15 UTC
Labels: duplicate
