### ISSUE TITLE
the lyrics are seen on the right in thumbnail, but they are not seen on the "open lyrics page"

### ISSUE THREAD

**Issue by Liudovik** [surfbryce/beautiful-lyrics#447] opened 2024-04-29 01:27 UTC
Hello, I wanted to inform you that I can't see the letters on the big screen, they are only seen on the right in miniature, I don't know if this happens to anyone else, but two months or so ago they stopped being seen. Thank you for the work you have done, greetings :3

![no se ven las letras](https://github.com/surfbryce/beautiful-lyrics/assets/27640275/6c040a72-d362-4d0a-bafe-df8ca1a40cf7)

**Comment by surfbryce** [comment] 2024-04-29 01:28
Duplicate of #441

**Closed by surfbryce** 2024-04-29 01:28 UTC
Labels: duplicate
