### ISSUE TITLE
Lyrics don't appear for this song

### ISSUE THREAD

**Issue by pizzabossxd** [surfbryce/beautiful-lyrics#251] opened 2024-01-19 00:00 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/68411735/7c074110-33b6-4535-9d91-5dfbd7980030)

The lyrics appear normal with the native Spotify Lyrics.

The lyrics are public and verified on Musixmatch and should appear inside the Beautiful Lyrics "Lyrics Page".

Theme name: Default

**Comment by surfbryce** [comment] 2024-02-16 12:16
Duplicate of #240

**Closed by surfbryce** 2024-02-16 12:16 UTC
Labels: duplicate
