### ISSUE TITLE
The lyrics page doesn't work for me.

### ISSUE THREAD

**Issue by ryhkaa** [surfbryce/beautiful-lyrics#388] opened 2024-04-12 17:22 UTC
I almost use the fullscreen lyrics or the "lyrics page" but it doesn't work for me anymore.

![Screenshot 2024-04-12 202119](https://github.com/surfbryce/beautiful-lyrics/assets/166856072/ed7bb30b-8566-4d9c-901e-f6838b222704)

it looks like this

**Comment by fastnlight0** [comment] 2024-04-12 17:45
*sigh* See issue #340

**Comment by surfbryce** [comment] 2024-04-12 17:45
Duplicate of #340

**Closed by surfbryce** 2024-04-12 17:45 UTC
Labels: duplicate
