### ISSUE TITLE
Fullscreen doesnt work for premium users

### ISSUE THREAD

**Issue by opiv** [surfbryce/beautiful-lyrics#483] opened 2024-05-09 17:15 UTC
Fullscreen doesnt work for premium users.

**Comment by TheUnrealZaka** [comment] 2024-05-09 18:53
Same but Free user

**Comment by boochySans** [comment] 2024-05-09 21:11
#441

**Comment by surfbryce** [comment] 2024-05-09 21:12
Duplicate of #441

**Closed by surfbryce** 2024-05-09 21:12 UTC
Labels: duplicate
