### ISSUE TITLE
Lyrics are right to left when they should be lift to right

### ISSUE THREAD

**Issue by awyeamrkrabs** [surfbryce/beautiful-lyrics#73] opened 2023-07-25 20:50 UTC
I'm having issues as of today, Jul 25 2023, where the lyrics are displayed right-to-left. It not only affects the alignment, but also the text itself. It only appears on some songs, not all. Here are an example. 

(The song below is called Diri by Tulus, it's in Indonesian)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/58422403/251b6ad5-bfe7-4ca6-8667-cdaa15733771)
Where it should be like this
![image](https://github.com/surfbryce/beautiful-lyrics/assets/58422403/86e5087a-ba09-4929-9dd0-441e6528e619)

For now, I can only find the issue in some song which are not English (in this case Indonesian). 

Can you please look into it? Thanks a lot:)

**Comment by surfbryce** [comment] 2023-07-25 20:51
@awyeamrkrabs I did notice this as well - even for some english songs - I think I know what's actually causing the issue so I'll take a look very soon.

**Comment by surfbryce** [comment] 2023-07-25 21:43
@awyeamrkrabs Alright I just pushed out a new update to fix this - I tested this with your song and with songs that should be right-aligned and everything seems to be perfect.

Wait a couple of minutes for it to auto-update OR restart Spotify and it should be on 3.1.6.

If the issue is fixed then let me know and I'll close this issue! Thank you for reporting!

**Closed** 2023-07-25 23:53 UTC
Labels: bug
