### ISSUE TITLE
Lyrics not visible

### ISSUE THREAD

**Issue by Jharenoo** [surfbryce/beautiful-lyrics#306] opened 2024-03-01 10:45 UTC
Fresh spotify install from the spotify website + fresh spicetify install.
Only installed the beautiful lyrics plugin thru market place, nothing else.
Free / Non premium account.
On opening fullscreen, there is a character that shows "Waiting For Update" upon hovering on it left to the lyrics button and under the progress bar.

**Comment by surfbryce** [comment] 2024-03-01 17:25
@Jharenoo Can you provide a screenshot? The "Waiting For Update" thing is not from my extension and is from Spotify I believe. So possibly reapplying Spicetify might work.

**Comment by AushevAhmad** [comment] 2024-03-03 15:41
I have same issue, here's a screenshot
![image](https://github.com/surfbryce/beautiful-lyrics/assets/113457231/ceedf9a4-380a-47f2-8def-fd12983b3564)

**Comment by mosheri** [comment] 2024-04-06 16:17
Yea I got the same exact issue can u fix it

**Comment by Reinified** [comment] 2024-04-06 20:54
this issue started for me yesterday, tried reinstalling the extension but nothing changed, even deleted full app display because I heard it clashes with it. 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/54984650/0c7b3a76-ab02-457a-8573-2a5b43dcd4e0)

**Comment by MohamedGoldberg** [comment] 2024-04-10 18:15
![Screenshot (1)](https://github.com/surfbryce/beautiful-lyrics/assets/166648929/4e22068a-fc0e-46ef-a5fe-97b919d45cb3)
when i click on it that's what appear 
i reinstalled windows and it still does not work 
(it was working)

**Comment by MohamedGoldberg** [comment] 2024-04-10 18:32
![image](https://github.com/surfbryce/beautiful-lyrics/assets/166648929/a039d066-dfbd-4e36-ba71-dc4abd64f827)
but the lyrics appear in the side-bar

**Comment by MohamedGoldberg** [comment] 2024-04-11 22:01
thx bro

**Comment by Aaqil30758** [comment] 2024-04-19 06:55
![image_2024-04-19_122421960](https://github.com/surfbryce/beautiful-lyrics/assets/116747739/9b79494d-acef-4822-9229-97653347d177)
Bro same issue, how do i fix this? Please say any solution

**Comment by Aaqil30758** [comment] 2024-04-19 06:56
> ![image](https://private-user-images.githubusercontent.com/166648929/321363221-a039d066-dfbd-4e36-ba71-dc4abd64f827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDk4NTAsIm5iZiI6MTcxMzUwOTU1MCwicGF0aCI6Ii8xNjY2NDg5MjkvMzIxMzYzMjIxLWEwMzlkMDY2LWRmYmQtNGUzNi1iYTcxLWRjNGFiZDY0ZjgyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwNjUyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjU4ZGQzNDZmMjUxM2M1YTNlYzJkZmQwNGU0OWVjZTc0MDVhZDZhNmJjMzFmYTEyZDAzZDkwZWZjMGFiNWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C3FTVkuCdyI6IkI6sDNdk3ORoYvgMawOFgsrwzy52Uk) but the lyrics appear in the side-bar

Bro, did u fix this? And how please say??

**Comment by Dika335** [comment] 2024-04-19 09:12
same here why thought?
![Screenshot (35)](https://github.com/surfbryce/beautiful-lyrics/assets/150528002/76993478-a5e4-4f1d-984a-555345bb11c2)

**Comment by MohamedGoldberg** [comment] 2024-04-22 19:04
just install an old spotify version

**Comment by MohamedGoldberg** [comment] 2024-04-22 19:05
just install an old spotify version

**Comment by abirabedinkhan** [comment] 2024-04-24 08:08
Duplicate of #340

**Comment by surfbryce** [comment] 2024-04-24 08:56
I want to make clear that this issue request is SEPARATE from the bug that occurred after the most recent Spotify updates. This is related to a different issue with the extension, I did end up confirming that the "Waiting for Update" indicator IS from my extension, is actually the placeholder text for the romanization button when it hasn't been used yet (the extension is obviously broken in this state since the romanization button shouldn't even appear IF the song can't be romanized).

I've only gotten this once, so I'll have to wait for it to happen again, hopefully the changes I've been making will fix this indirectly.

**Comment by surfbryce** [comment] 2024-05-15 17:55
Should be fixed in the latest update

**Closed by surfbryce** 2024-05-15 17:55 UTC
Labels: invalid
