### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by mgozdzik701** [surfbryce/beautiful-lyrics#384] opened 2024-04-11 11:26 UTC
Clicking beautiful lyrics button but since new update old lyrics work but these not (I mean it opens but there are no lyrics or color background)
#340 #306 #382 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/152547876/4917f282-a1d0-418f-b622-c2e104381a92)

**Comment by surfbryce** [comment] 2024-04-11 16:33
Duplicate of #340

**Closed by surfbryce** 2024-04-11 16:33 UTC
Labels: duplicate
