### ISSUE TITLE
The lyrics page does not appear

### ISSUE THREAD

**Issue by SyachruRizky** [surfbryce/beautiful-lyrics#377] opened 2024-04-10 05:05 UTC
I don't know why it doesn't work

If I press the lyrics page or not open the lyrics page, only a blank page appears

![image](https://github.com/surfbryce/beautiful-lyrics/assets/105147021/9b4ee49e-5db4-4bbd-81bd-c400b0347a3b)

but for the right side it's fine

![image](https://github.com/surfbryce/beautiful-lyrics/assets/105147021/9a05ef9f-e02a-4240-a1a1-610be8f1b87c)

**Comment by gbrlldcsn** [comment] 2024-04-10 05:08
i have the same problem

**Comment by SyachruRizky** [comment] 2024-04-10 05:10
I've uninstalled Spotify and reinstalled it. the result is the same

**Comment by surfbryce** [comment] 2024-04-10 05:38
Duplicate of #340

**Closed by surfbryce** 2024-04-10 05:38 UTC
Labels: duplicate
