### ISSUE TITLE
Fullscreen not working

### ISSUE THREAD

**Issue by xcau** [surfbryce/beautiful-lyrics#381] opened 2024-04-10 19:58 UTC
Lyrics works perfectly fine on the side bar but doesn't show when trying to open on fullscreen. Anyone solved this or? 
I tried reloading and reinstalling spicetify multiple times nothing solved it, the plugin worked perfectly fine a week ago.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/83733099/a4aa5c3c-73bc-4ea7-91bb-36d6df294587)

**Comment by Magniquick** [comment] 2024-04-10 20:14
Can confirm that native spotify fullscreen is broken
[custom ones](https://github.com/daksh2k/Spicetify-stuff/blob/master/Extensions/full-screen/README.md) still work tho.

**Comment by surfbryce** [comment] 2024-04-10 20:15
Duplicate of #340

**Closed by surfbryce** 2024-04-10 20:15 UTC
Labels: duplicate
