### ISSUE TITLE
[Bug]: Not working

### ISSUE THREAD

**Issue by titopalana123** [surfbryce/beautiful-lyrics#646] opened 2024-05-27 21:53 UTC
### Bug Report Checklist

- [X] **If you are making a Bug Report about the Extension being broken in some way, read this**: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#there-is-something-wrong-with-the-extension-not-lyrics
- [X] **If you are making a Bug Report about Lyrics in some way, read this**: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version

### What happened?

none song i try works
![image](https://github.com/surfbryce/beautiful-lyrics/assets/170983344/9591a998-e148-4e6f-a490-9eb2888a46b1)
<img width="1584" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/170983344/365cffb4-12dc-48d5-a3be-5a5eacf0792d">

### The country you are from

Spain

### Spotify/Spicetify Version

Spotify: 1.2.35.720.ga4a70a0e  Spicetify v2.36.11

### What os are you seeing the problem on?

Windows

**Comment by titopalana123** [comment] 2024-05-27 21:54
i dont have premium if it is the problem

**Comment by NotAmiru** [comment] 2024-05-27 23:08
> i dont have premium if it is the problem

its not a premium issue the plugin hasnt been working for roughly a month and the dev has said that he plans to release a fix as soon as he can

**Comment by surfbryce** [comment] 2024-05-28 01:38
@titopalana123 This is a duplicate of existing issues, this will be fixed in the next patch

**Closed by surfbryce** 2024-05-28 01:38 UTC
Labels: Extension Bug
