### ISSUE TITLE
The lyrics don't show up after I toggle full screen mode

### ISSUE THREAD

**Issue by Satvik71** [surfbryce/beautiful-lyrics#422] opened 2024-04-23 17:44 UTC
![Spotify Free 23-04-2024 23_13_43](https://github.com/surfbryce/beautiful-lyrics/assets/167907566/bff9b705-f4a8-4768-9f46-0245ade59e78)

**Comment by surfbryce** [comment] 2024-04-23 18:44
Duplicate of #340

**Closed by surfbryce** 2024-04-23 18:44 UTC
Labels: duplicate
