### ISSUE TITLE
Lyrics not showing up

### ISSUE THREAD

**Issue by grusenova** [surfbryce/beautiful-lyrics#285] opened 2024-02-15 14:21 UTC
The lyrics is not showing up, Anyone knows on how to fix this?

![Screenshot 2024-02-15 211910](https://github.com/surfbryce/beautiful-lyrics/assets/149503191/0b5ec546-09c1-4f98-92c9-f884c7f1376f)

**Comment by godisopensource** [comment] 2024-02-15 21:48
Same problem here. If you head up to the top of the page, does it show you a "Waiting for update" button? If so I think it can help the developer fix the issue because it is more precise than "lyrics not showing up" and it would be a global issue.
![Capture d’écran 2024-02-15 à 22 47 32](https://github.com/surfbryce/beautiful-lyrics/assets/101464040/0e836c7d-14de-4c77-ad37-6c849065575c)

**Comment by TechnoStone** [comment] 2024-02-15 21:58
Same here, also shows up "Waiting For Update"

**Comment by godisopensource** [comment] 2024-02-15 22:00
Is it since you last updated Spotify? I am asking because it is my case. Updated Spotify desktop today and this caused Beautiful Lyrics to stop working.

**Comment by TechnoStone** [comment] 2024-02-15 22:04
Can't say anything special, today I've updated all the software (including spotify and spicetify) on all my PCs and OSes on them and plugin began showing empty lyrics on laptop on Windows. Gonna reboot to macOS to check out

**Comment by godisopensource** [comment] 2024-02-15 22:06
Same situation on macOS.

**Comment by TechnoStone** [comment] 2024-02-15 22:12
This is kinda strange
<details>
  <summary>Images</summary>

![PXL_20240215_220629699](https://github.com/surfbryce/beautiful-lyrics/assets/26044948/4ca92b0e-633b-4bf8-aed5-e4a483415792)

![PXL_20240215_220821313](https://github.com/surfbryce/beautiful-lyrics/assets/26044948/07127494-31d6-4cef-a9ed-0d163f061cb9)

![PXL_20240215_221049599](https://github.com/surfbryce/beautiful-lyrics/assets/26044948/3e253a1a-ac15-4fe0-99e3-35528521ae4e)
</details>

**Comment by godisopensource** [comment] 2024-02-15 22:20
Yeah, depends on the music you play (and it loads for random songs...). Let's wait for the developer to see this issue then. 
_Beautiful hackintosh btw :)_

**Comment by Kamiien** [comment] 2024-02-15 22:48
I found a workaround: just download older version from this website [https://spotify.en.uptodown.com/windows/versions](https://spotify.en.uptodown.com/windows/versions)

**Comment by surfbryce** [comment] 2024-02-16 12:18
Duplicate of #240

**Closed by surfbryce** 2024-02-16 12:18 UTC
Labels: duplicate
