### ISSUE TITLE
Gray screen

### ISSUE THREAD

**Issue by Jo20pxd** [surfbryce/beautiful-lyrics#382] opened 2024-04-11 00:29 UTC
My lyrics only appear small on the ‘Listening Now’ tab. On the fullscreen tab, it just turns gray and doesn’t work.
![Captura de tela 2024-04-10 212917](https://github.com/surfbryce/beautiful-lyrics/assets/105810290/128da92b-c22e-4aba-91c9-dfa07b4fa63f)

**Comment by PikzAlex** [comment] 2024-04-11 01:56
Same issue but I'm also missing the lyrics on the 'Listening Now' sidebar.

**Comment by CRYPTIX-hub** [comment] 2024-04-11 01:57
Same issue with me.

**Comment by AndrewMaged814** [comment] 2024-04-11 02:08
same issue

**Comment by lopyo-art** [comment] 2024-04-11 02:18
Exactly the same.

**Comment by surfbryce** [comment] 2024-04-11 02:30
Duplicate of #340

**Closed by surfbryce** 2024-04-11 02:30 UTC
Labels: duplicate
