### ISSUE TITLE
Lyrics don't show on new songs with lyrics

### ISSUE THREAD

**Issue by nulIz** [surfbryce/beautiful-lyrics#192] opened 2023-11-12 18:58 UTC
This applies for the Heaven Knows album by Pinkpantheress, and thats the only instance I have right now. Before,  the song Capable of Love also had the same issue, but it said, "This song doesn't have lyrics." (Even though it did.) But it resolved itself later. This one doesn't even have "This song doesnt have lyrics."

**Comment by surfbryce** [comment] 2023-11-15 04:32
Duplicate of #155, but also I didn't change the title to properly indicate the issue so I should do that. If you can comment on that post with these examples that'd be great, thank you

**Closed by surfbryce** 2023-11-15 04:32 UTC
Labels: duplicate

**Comment by nulIz** [comment] 2023-11-15 13:39
The difference between mine and his is that it doesnt say "This song doesn't have any lyrics!", its just a blank screen but with the cinematic in the background. The song does have lyrics as I used lyrics plus to check if it does.
