### ISSUE TITLE
Lyrics not showing up at all

### ISSUE THREAD

**Issue by ItzGhenes1s** [surfbryce/beautiful-lyrics#386] opened 2024-04-12 07:43 UTC
**I have uninstalled spotify and re downloaded it multiple times but the lyrics still aren't popping up**

![image](https://github.com/surfbryce/beautiful-lyrics/assets/166799451/945669b4-31cd-4a90-b46e-380e20e3dc7b)

**Comment by kzin123** [comment] 2024-04-12 07:58
I have same issue

**Comment by christiancandelario** [comment] 2024-04-12 15:50
same isssue here it's been a week since that happened

**Comment by AADI777BH** [comment] 2024-04-12 16:05
I AM HAVING SAME ISSUE THE LYRICS NOT SHOWING 3 DAYS AGO PLEASE FIX IT :(

**Comment by surfbryce** [comment] 2024-04-12 16:44
Duplicate of #340

**Closed by surfbryce** 2024-04-12 16:44 UTC
Labels: duplicate
