### ISSUE TITLE
No lyrics when fullscreened - Haze theme

### ISSUE THREAD

**Issue by wn7r** [surfbryce/beautiful-lyrics#351] opened 2024-04-05 07:22 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/91768237/a006a28a-7091-40d1-8111-403f59f3cb51)

**Comment by bleghj** [comment] 2024-04-05 07:34
Similar issues

**Comment by shaadmhd** [comment] 2024-04-05 11:26
same issue on haze theme

**Comment by surfbryce** [comment] 2024-04-05 14:22
Duplicate of #340

**Closed by surfbryce** 2024-04-05 14:22 UTC
Labels: duplicate
