### ISSUE TITLE
Beautiful not working - Spicetify

### ISSUE THREAD

**Issue by TrigerG** [surfbryce/beautiful-lyrics#396] opened 2024-04-14 12:53 UTC
Hi, I have been using spicetify and Beautiful Lyrics extension is not working have tried re-installing spicetify and the extension multiple times but still its not working.

Please fix it ASAP!

**Comment by surfbryce** [comment] 2024-04-14 17:13
Duplicate of #340

**Closed by surfbryce** 2024-04-14 17:13 UTC
Labels: duplicate
