### ISSUE TITLE
The Beautiful Lyrics is not from the middle, but the playing view is working!

### ISSUE THREAD

**Issue by JCTasaTech** [surfbryce/beautiful-lyrics#372] opened 2024-04-09 02:11 UTC
![Screenshot 2024-04-09 100756](https://github.com/surfbryce/beautiful-lyrics/assets/166354349/2fbbc2e0-dbe4-4a2e-bdc5-272def72a751)

**Comment by surfbryce** [comment] 2024-04-09 02:20
Duplicate of #340

**Closed by surfbryce** 2024-04-09 02:20 UTC
Labels: duplicate
