### ISSUE TITLE
[Bug]: Lyrics never load

### ISSUE THREAD

**Issue by zeus3du** [surfbryce/beautiful-lyrics#651] opened 2024-05-28 20:55 UTC
### Bug Report Checklist

- [X] **If you are making a Bug Report about the Extension being broken in some way, read this**: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#there-is-something-wrong-with-the-extension-not-lyrics
- [X] **If you are making a Bug Report about Lyrics in some way, read this**: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version

### What happened?

The lyrics are just infinitely loading.

### The country you are from

Portugal

### Spotify/Spicetify Version

Spotify for Windows (64 bit) 1.2.38.720.ga4a70a0e Spicetify v2.36.11

### What os are you seeing the problem on?

Windows

### Spotify HTML/CSS files when the Issue is ACTIVELY happening

[Spotify.css.txt](https://github.com/surfbryce/beautiful-lyrics/files/15475917/Spotify.css.txt)
[Spotify.html.txt](https://github.com/surfbryce/beautiful-lyrics/files/15475918/Spotify.html.txt)

### Screenshot of the entire Console

![image](https://github.com/surfbryce/beautiful-lyrics/assets/170748366/9419fcee-11b9-42f6-a2dd-542f9d38dfe2)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/170748366/f762a550-5d4e-4d2e-9992-75bd2c6a4fff)

**Comment by nanocodium** [comment] 2024-05-28 23:07
same for me

**Comment by surfbryce** [comment] 2024-05-28 23:08
@zeus3du Thank you so much for reporting, this is a duplicate of existing issues and will be fixed in the next patch

**Closed by surfbryce** 2024-05-28 23:08 UTC
Labels: Extension Bug, Duplicate
