### ISSUE TITLE
lyrics only working on side bar and doesnt let me go full screen

### ISSUE THREAD

**Issue by 13randn** [surfbryce/beautiful-lyrics#358] opened 2024-04-06 09:04 UTC
im trying to put the lyrics in the full screen mode by clicking "open lyrics page" but it just brings me to a blank screen. im on pc

**Comment by somewhat69** [comment] 2024-04-06 10:03
yeah

**Comment by surfbryce** [comment] 2024-04-06 14:13
Duplicate of #340

**Closed by surfbryce** 2024-04-06 14:13 UTC
Labels: duplicate
