### ISSUE TITLE
i cannot see the lyrics pls

### ISSUE THREAD

**Issue by ukuygilgli** [surfbryce/beautiful-lyrics#594] opened 2024-05-21 11:56 UTC
**If you are making a Bug Report about the Extension being broken in some way, read this**:
https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#there-is-something-wrong-with-the-extension-not-lyrics

**If you are making a Bug Report about Lyrics in some way, read this**:
https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version

**IF YOU DO NOT FOLLOW EITHER INSTRUCTIONS, YOUR BUG-REPORT WILL BE INSTANTLY DELETED**
![image](https://github.com/surfbryce/beautiful-lyrics/assets/170425678/621767d8-68e8-410f-8190-55583a8ebfbe)

**Comment by surfbryce** [comment] 2024-05-21 19:29
Duplicate of #502

**Closed by surfbryce** 2024-05-21 19:29 UTC
Labels: Duplicate
