### ISSUE TITLE
swapping from the dj right panel to a song causes lyrics widget to not show

### ISSUE THREAD

**Issue by ohitstom** [surfbryce/beautiful-lyrics#518] opened 2024-05-16 10:48 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/22730962/1d930893-49c0-4c5f-b1e3-1f9c413831d2)

**Comment by surfbryce** [comment] 2024-05-27 06:57
@ohitstom Will be fixed in the next patch, was caused by the nowPlayingWidget being changed in place and an old reference to it being used because of that.

**Closed** 2024-05-29 19:42 UTC
Labels: Extension Bug, In Next Patch
