### ISSUE TITLE
Lyrics issues.

### ISSUE THREAD

**Issue by NadeemZayed** [surfbryce/beautiful-lyrics#380] opened 2024-04-10 14:52 UTC
Hello there! my current issue is the lyrics isn't showing when I click on Beautiful lyrics icon I don't have any modifications except Beautiful-lyrics and ad-blocker. when clicked on beautiful lyrics icon on bottom right it sends me into a blank canvas with no lyrics of the song selected (by blank I mean grey no animations of the background or anything of the matter) and it doesn't highlight the beautiful lyrics icon and I don't know if it should highlight like glow green constantly if clicked but that's my case I hope you can help.

**Comment by surfbryce** [comment] 2024-04-10 17:18
Duplicate of #340

**Closed by surfbryce** 2024-04-10 17:18 UTC
Labels: duplicate
