### ISSUE TITLE
Do you need premium to make it work? Stuck on loading...

### ISSUE THREAD

**Issue by Gitsstates** [surfbryce/beautiful-lyrics#495] opened 2024-05-15 14:44 UTC
I just finished setting up Spicetify and added all the necessary files, including the marketplace and extensions. However, the lyrics karaoke feature seems to be stuck on an endless load. Has Spotify’s restriction of lyrics access to non premium users made it necessary to upgrade for this feature?

![image](https://github.com/surfbryce/beautiful-lyrics/assets/152910993/7ab6aad1-844e-4204-a921-c23499091713)

**Comment by theolensky** [comment] 2024-05-15 14:58
Look at Issue #441 please

**Comment by boochySans** [comment] 2024-05-15 16:23
Duplicate of https://github.com/surfbryce/beautiful-lyrics/issues/441

**Comment by surfbryce** [comment] 2024-05-15 16:24
Duplicate of #441

**Closed by surfbryce** 2024-05-15 16:24 UTC
Labels: duplicate
