### ISSUE TITLE
It just doesn't show up at all

### ISSUE THREAD

**Issue by jonathankonda** [surfbryce/beautiful-lyrics#385] opened 2024-04-11 22:29 UTC
Ever since I updated Spotify, lyrics don't show up and it's just a blank page.

**Comment by keegs190001** [comment] 2024-04-11 23:53
I can second this, I click on the microphone icon to launch it and the page that appears is just blank. Nothing at all.

**Comment by fastnlight0** [comment] 2024-04-12 00:17
Duplicate of #340

**Comment by surfbryce** [comment] 2024-04-12 00:40
Duplicate of #340

**Closed by surfbryce** 2024-04-12 00:40 UTC
Labels: duplicate
