### ISSUE TITLE
The lyrics seem to be in a completely AWFUL font.

### ISSUE THREAD

**Issue by Tencta** [surfbryce/beautiful-lyrics#246] opened 2024-01-12 13:34 UTC

**Comment by Tencta** [comment] 2024-01-12 13:35
![image](https://github.com/surfbryce/beautiful-lyrics/assets/85408331/8000be96-2f76-4c37-b75e-196c661dd804)

**Comment by surfbryce** [comment] 2024-02-16 12:24
Duplicate of #245

**Comment by surfbryce** [comment] 2024-02-16 12:25
@Tencta This tends to be an issue with internet connection/loading, is this still happening for you?

**Comment by surfbryce** [comment] 2024-05-15 17:33
New update has different mechanism for CSS, might fix issue, re-create the issue if it happens again

**Closed by surfbryce** 2024-05-15 17:33 UTC
Labels: invalid

**Comment by adhamdawild** [comment] 2024-06-20 19:30
did you ever figure it out?
