### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Hamy08** [surfbryce/beautiful-lyrics#392] opened 2024-04-13 18:43 UTC
![Screenshot 2024-04-13 214115](https://github.com/surfbryce/beautiful-lyrics/assets/166948509/23837a33-c0b1-4139-86ab-1f71e0afc528)
So basically a friend me abt spicetify and this lyrics thing, i downloaded it and it worked amazingly as spotify wasnt really showing any lyrics it worked perfect for almost a month but suddenly it just went blank.
i updated spotify and spicetify
deleted and reinstalled spotify 
but yet the problem stayed :/

**Comment by surfbryce** [comment] 2024-04-13 18:44
Duplicate of #340

**Closed by surfbryce** 2024-04-13 18:44 UTC
Labels: duplicate
