### ISSUE TITLE
lyrics not showing up + full screen messed up

### ISSUE THREAD

**Issue by juanisola** [surfbryce/beautiful-lyrics#332] opened 2024-03-23 19:38 UTC
how can I fix this? thanks 
<img width="1467" alt="Captura de pantalla 2024-03-23 a la(s) 16 37 16" src="https://github.com/surfbryce/beautiful-lyrics/assets/104380950/210f8ab7-3524-4af6-b0af-83156e70a7c5">
<img width="1470" alt="Captura de pantalla 2024-03-23 a la(s) 16 37 22" src="https://github.com/surfbryce/beautiful-lyrics/assets/104380950/a23373a4-0282-43fd-b425-fa42c03d807b">

**Comment by iwandaferdi** [comment] 2024-03-24 09:04
I have the same problem here

**Comment by Robinjaquez** [comment] 2024-03-24 18:03
i had the same error, what i did was uninstall my spotify version and install the oldest one, then install specify and all runs how it should be

**Comment by surfbryce** [comment] 2024-04-03 19:46
Duplicate of #327

**Closed by surfbryce** 2024-04-03 19:46 UTC
Labels: duplicate
