### ISSUE TITLE
not really a bug but an idea

### ISSUE THREAD

**Issue by Bageang** [surfbryce/beautiful-lyrics#595] opened 2024-05-21 12:29 UTC
maybe it would be if you could add escape key functionality so we can exit the lyrics screen or full screen mode. maybe make it compatible with the hazy theme as well so the background in the media player and lyrics page is translucent instead of the dyanmic background and we can enable and disable

**Comment by surfbryce** [comment] 2024-05-21 19:30
Duplicate of #505

**Closed by surfbryce** 2024-05-21 19:30 UTC
Labels: Duplicate
