### ISSUE TITLE
High system resources usage

### ISSUE THREAD

**Issue by PIndividual** [surfbryce/beautiful-lyrics#690] opened 2024-06-02 11:53 UTC
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

I'm using hazy as my Spotify theme and when I combine it with beautiful lyrics, I'm experiencing constant frame drops and high CPU and graphics usage. 

### What is your Suggestion?

Disabling the blurred background may help solve this issue, and also promote better consistency with the theme. There can be an option for that.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by loawld432** [comment] 2024-06-02 23:24
Dude I'm pretty sure this has been an issue since the extension came out, just close the lyrics whenever you're playing something or tabbed out

**Comment by surfbryce** [comment] 2024-06-03 20:48
Duplicate of #185

**Closed by surfbryce** 2024-06-03 20:48 UTC
Labels: Duplicate, Suggestion
