### ISSUE TITLE
THEME Default Dynamic issues

### ISSUE THREAD

**Issue by Tyrannous** [surfbryce/beautiful-lyrics#427] opened 2024-04-24 10:12 UTC
![Screenshot 2024-04-24 041130](https://github.com/surfbryce/beautiful-lyrics/assets/23184602/7e7580b0-a4a5-41f0-bed7-8eda0129b705)

Lyrics aren't showing up when program is just maximized/main window, just the animated background.

**Comment by RedolentHalo** [comment] 2024-04-24 16:34
I've the same problem this is after the spotify update

**Comment by srijithmass** [comment] 2024-04-24 16:41
Even full screen too not working.

**Comment by RedolentHalo** [comment] 2024-04-24 16:55
> Even full screen too not working.

Yea

**Comment by surfbryce** [comment] 2024-04-24 19:39
Duplicate of #340

**Closed by surfbryce** 2024-04-24 19:39 UTC
Labels: duplicate
