### ISSUE TITLE
issue with the lyrics 

### ISSUE THREAD

**Issue by IIcydi** [surfbryce/beautiful-lyrics#421] opened 2024-04-23 14:26 UTC
i use theme DefaultDynamic
![image](https://github.com/surfbryce/beautiful-lyrics/assets/167888838/f13918f5-a302-40ab-983e-7ca81b312163)
Lyrics are not displayed & when full screen
![image](https://github.com/surfbryce/beautiful-lyrics/assets/167888838/2241f0a8-01a9-4000-b7bd-bb9fda4ec04c)

**Comment by surfbryce** [comment] 2024-04-23 18:43
Duplicate of #340

**Closed by surfbryce** 2024-04-23 18:43 UTC
