### ISSUE TITLE
Super Laggy

### ISSUE THREAD

**Issue by bhxp** [surfbryce/beautiful-lyrics#716] opened 2024-06-07 21:24 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Beautiful Lyrics causes high memory usage, and it lags very bad, but on songs where they don't have the dynamic thing, it doesn't lag, even with a super good computer.

### What Country are you from?

United States

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.39.578.g0ea3f38b
Spotify Runtime: cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Spicetify Version: 2.36.12
Spicetify Theme: Galaxy / base
Spicetify Extensions: [adblock.js, fullAppDisplayMod.js, fullScreenWrapper.js, volumePercentage.js, cacheCleaner.js, bfs-bundle.js, beautiful-lyrics.js, beautiful-lyrics.mjs, content.js, simple-beautiful-lyrics.js, enhancePlus.js, spotdj.js, theme.js]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

tried putting things here but i couldent

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment] 2024-06-07 21:30
@bhxp Duplicate of #185, this will be handled soon.

**Closed by surfbryce** 2024-06-07 21:30 UTC
Labels: Extension Bug, Duplicate

**Comment by bhxp** [comment] 2024-06-12 21:50
i fixed it, apparently it was running the Microsoft store version, so I reinstalled from the exe and it fixed issues
