### ISSUE TITLE
Still not working fullscreen mode as of updated version in April 19 2024

### ISSUE THREAD

**Issue by christiancandelario** [surfbryce/beautiful-lyrics#415] opened 2024-04-22 05:39 UTC
So you updated this on April 19, 2024, but I tried now (April 22, 2024) to reinstall Spotify and Spicetify to their updated versions, but still, if I press the fullscreen button, it still doesn't work. How can I fix this? I really love your interface but why this doesn't work?
![Screenshot 2024-04-22 133801](https://github.com/surfbryce/beautiful-lyrics/assets/72423044/840179b5-0733-48ed-bc14-f4e8fbe2bc1f)

**Comment by surfbryce** [comment] 2024-04-22 05:40
Duplicate of #340, there was no update made, there hasn't been for over two months!

**Closed by surfbryce** 2024-04-22 05:40 UTC
Labels: duplicate
