### ISSUE TITLE
Share lyric picture

### ISSUE THREAD

**Issue by monewm** [surfbryce/beautiful-lyrics#791] opened 2024-07-20 20:58 UTC
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

it would make sharing spotify lyrics more beautiful, better than the spotify one, 
(I left an image below to show how bad it is right now)

### What is your Suggestion?

to make a built-in app lyrics picture system, and the ability to select some lyrics of the song and save it in various resolutions, such a one for Instagram story.
![image](https://github.com/user-attachments/assets/866cb046-664a-43e0-9037-b88d957c104a)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment] 2024-07-27 16:19
@monewm Duplicate of #754

**Closed by surfbryce** 2024-07-27 16:19 UTC
Labels: Duplicate, Suggestion
