### ISSUE TITLE
(Bug) Best Lyric Sync-Mode Not Available

### ISSUE THREAD

**Issue by enzon19** [surfbryce/beautiful-lyrics#171] opened 2023-10-09 17:52 UTC
I was using Musixmatch on Android and I noticed that "Given Up" from Linkin Park has word by word sync, but when I played on PC with Beautiful Lyrics there wasn't word by word sync. 

![image](https://github.com/surfbryce/beautiful-lyrics/assets/89558747/e28b36d7-e6e9-43c7-be53-70ab5df75b3d)

I thought the lyrics came from Musixmatch (#148 and #143), is that right? Why is not available?

**Comment by surfbryce** [comment] 2023-10-09 18:02
@enzon19 So I can confirm that the song should be syllable synced. Apple Music is the primary source-provider but even they also have syllable synced lyrics.

The reason why I mention Musixmatch so much is because all of these music services use Musixmatch at the end of the day to source their lyrics. The only difference between Apple and everybody else is that they also have their own artist/label program which has some lyrics that Musixmatch does not. Musixmatch as of now is not being utilized whatsoever directly but that'll change in the future as a drop-in replacement for Spotify as a source (since Spotify is now forcing lyrics to be Premium only).

I'm not sure what's going on here specifically since when I deleted the cached version of the lyrics it's still returning the line-synced lyrics. So I'll have to investigate this but this is absolutely a bug somewhere - I just don't what specifically.

**Comment by oldschoolvirgo** [comment] 2023-10-09 18:47
@surfbryce i would love to support the app and your contributions. Any plans to put up a crowdfunding link like Buy Me a Coffee?

**Comment by surfbryce** [comment] 2023-10-09 18:52
@enzon19 I think you misunderstood what I said. It's not an issue with Apple. Apple *does* have syllable-synced lyrics for that song. It's an issue with my backend that I haven't exactly diagnosed what the issue is.

Also just to note that I do not scrape, I use the documented APIs for these services that I use.

This has nothing to do with the rate of propagation for Musixmatch, Apple Music, or whoever else; it is simply an issue on my end which is why I marked it as a bug.

Just reiterating to make the issue here clear in case anybody else comes across this.

**Comment by surfbryce** [comment] 2023-10-09 18:55
@oldschoolvirgo I appreciate the sentiment but there are no plans to put up any crowdfunding ever. I produce/develop this extension for my own benefit (I originally made this so I could have a gradient background and then that evolved into Apple Music styled lyrics); anything else that is suggested is just done because the community is owed a better lyrics experience for free. Appreciate the thought!

**Comment by enzon19** [comment] 2023-10-09 19:01
> It's not an issue with Apple. Apple _does_ have syllable-synced lyrics for that song. It's an issue with my backend that I haven't exactly diagnosed what the issue is.

Oh, lol. Sorry. When you said that Apple Music "also have syllable synced lyrics" I thought you are saying in general, like they also offer this type of sync that you can get.

Now I understood the problem. Thanks again and thanks for the amazing extension!

**Comment by AgentMonkey00** [comment] 2023-10-17 19:49
Just adding my thoughts:
I've noticed for a lot of songs it happens regardless of how long the lyrics have been synced on Musixmatch. 

Some examples of songs that are synced word-by-word on Musixmatch but not the extension:
Big Plans - Why Don't We                  8 Letters - Why Don't We                  Nothing New - Fly By Midnight                  Setotonin - Tom Walker
There are lots of other examples from other artists too!

I know it's already been said too but @surfbryce you should really consider setting up a tip system. Not a paywall, just a donation-type thing. I would love to support the work too!!

**Comment by calicokatsu** [comment] 2023-11-03 03:31
@surfbryce I was wondering whether or not it was because in your Lyrics Parser, you assume all non-Apple Music lyrics are line-synced? Not entirely sure but just an idea

**Comment by surfbryce** [comment] 2023-11-03 04:06
> @enzon19 I think you misunderstood what I said. It's not an issue with Apple. Apple _does_ have syllable-synced lyrics for that song. It's an issue with my backend that I haven't exactly diagnosed what the issue is.
> 
> Also just to note that I do not scrape, I use the documented APIs for these services that I use.
> 
> This has nothing to do with the rate of propagation for Musixmatch, Apple Music, or whoever else; it is simply an issue on my end which is why I marked it as a bug.
> 
> Just reiterating to make the issue here clear in case anybody else comes across this.

@calicokatsu please read the conversation prior to commenting to make sure you're up to date on the topic.

The LyricsParser only supports Apple Music and Spotify sources at the moment. Apple Music is used for every type of source if available (Syllable, Line, and Static). Spotify is only ever used for Line-Sync (Syllable would be an option if they provided it, which they do not). This is why the LyricsParser only does line-sync parsing for Spotify because that's the only option we provide. Apple Music supports all three because we provide all three.

As I mentioned, this is an issue with my backend. Apple Music has syllable-synced lyrics my backend is just not providing them properly. This is because of a caching issue which I have identified and plan to fix.

**Comment by calicokatsu** [comment] 2023-11-03 04:19
oh okay I understand now

**Comment by iPixelGalaxy** [comment] 2024-02-22 21:52
Hey I noticed this is quite an old thread, are there any plans to have this issue addressed? Love the work you do man, thank you for providing me an awesome lyric player experience to stream into VRC video players ❤️
![image](https://github.com/surfbryce/beautiful-lyrics/assets/42526028/f30e6c4d-fafd-4b0f-8772-ecf8e34f288e)

**Comment by surfbryce** [comment] 2024-02-22 23:17
@iPixelGalaxy Thanks for the kind words, but it would've been helpful to have had a screenshot of a song that doesn't have the best possible lyrics mode on Beautiful Lyrics, in #291 I talk about an approach that would fix a lot of songs with missing lyrics (I explain why it's like that as of now) and this same approach would also improve the sync mode of lyrics because we would have a wider range to work with.

**Comment by iPixelGalaxy** [comment] 2024-02-22 23:56
> Thanks for the kind words, but it would've been helpful to have had a screenshot of a song that doesn't have the best possible lyrics mode on Beautiful Lyrics
Oh yea here is a song I added word by word sync on Musixmatch that doesn't have it unfortunately 
https://open.spotify.com/track/1LMEdkcf0eaod1LGLpvpGg

**Comment by surfbryce** [comment] 2024-02-23 00:04
Ah @iPixelGalaxy that's a different issue, I primarily use Apple Music with Spotify as a backup on the client, I'm moving a lot of the Spotify stuff to my backend, but I might just replace Spotify with Musixmatch instead.

Either way, Apple Music only updates so fast, and same with my backend. Right now for a song with line-synced lyrics it'll only update every month, if it has no lyrics at all it'll update every day.

So we'll see, I'll definitely look into supporting Musixmatch directly rather than through Spotify, should account for cases like you mentioned, where you personally add synced lyrics through Musixmatch.

**Comment by enzon19** [comment] 2024-02-23 00:16
Just to add more musics (without the best lyrics mode) to the list... I don't have Apple Music to check if they are available there, so I'm taking Musixmatch as reference

- Given Up - Linkin Park
- Change (In the House of Flies) - Deftones
- Helicopter - Bloc Party

I'll updating this list as soon as I found more musics!

**Comment by iPixelGalaxy** [comment] 2024-03-17 14:40
> So we'll see, I'll definitely look into supporting Musixmatch directly rather than through Spotify, should account for cases like you mentioned, where you personally add synced lyrics through Musixmatch.

Btw do you need access to the Musixmatch API, or is that something I might be able to help push forward, I have access to the curator slack discord, so I could probably put in a word or something :)

**Comment by surfbryce** [comment] 2024-05-15 17:49
Everything here now has lyrics using the new Lyrics Service, thanks for the report!

**Closed by surfbryce** 2024-05-15 17:49 UTC
Labels: bug
