### ISSUE TITLE
right sidebar unchanged 

### ISSUE THREAD

**Issue by magnusssz** [surfbryce/beautiful-lyrics#26] opened 2023-05-30 01:53 UTC
for some reason, my right sidebar returned to default. it was working when I first installed the extension

![image](https://github.com/surfbryce/beautiful-lyrics/assets/99515102/38e06381-739d-4526-9802-1a020124c511)

full screen is working normally

**Comment by surfbryce** [comment] 2023-05-30 01:54
Can you send me which Spotify/Spicetify version you are on?

You should be able to see it by going to Spotify > About Spotify - on Windows you can right click the top of the window to view that

**Comment by magnusssz** [comment] 2023-05-30 01:55
sure
![Spotify_2023-05-29_22-55-19](https://github.com/surfbryce/beautiful-lyrics/assets/99515102/e90a73e1-8c4f-4660-864e-99b9294e82cb)

**Comment by surfbryce** [comment] 2023-05-30 01:56
Weird - I would try restarting Spotify and see if that changes anything. If it doesn't - would you mind showing which extensions/apps you have installed?

**Comment by magnusssz** [comment] 2023-05-30 02:03
restarted spotify many times already, no change. i've actually got your extension a couple of hours ago, running 2.4.1

have these extensions/snippets installed:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/99515102/1247a3dc-0b31-4a06-b59d-eaded842f8f3)
![Spotify_2023-05-29_22-58-00](https://github.com/surfbryce/beautiful-lyrics/assets/99515102/049408ab-b7a0-418e-9f26-2972dbafe2f1)

lyrics-plus and statistics apps only

**Comment by surfbryce** [comment] 2023-05-30 02:08
Can you run Spotify with dev-tools enabled? I usually don't ask because it's too out of the way for most people - but - I really have no clue what could be causing this?

To do that go into your terminal/command prompt and run spicetify apply enable-devtools

If it fails to open just run it again.

Then right click on the card and click "Show DevTools" - click on the console tab and screenshot everything that is there.

**Comment by magnusssz** [comment] 2023-05-30 02:23
here it is
![image](https://github.com/surfbryce/beautiful-lyrics/assets/99515102/36eaa201-b0f7-4e6e-8e2e-2e0a603d3118)

**Comment by surfbryce** [comment] 2023-05-30 02:28
Hmmn doesn't seem like my extension is having any issues.... would you mind;
- Clicking the little rounded rectangle with a cursor icon in the top left near the Elements tab
- Then clicking on your Spotify window to focus it
- And then hovering over the top of the right-sidebar inbetween the gap between the title text and the very top edge to select it
- And then clicking that space
- And then going back to the Elements tab in the DevTools
- And then scrolling so that the selected item (highlighted in blue) is about 75% down the little Elements window (this is so I can see the other elements above it including the element you selected)

**Comment by magnusssz** [comment] 2023-05-30 02:31
like this?
![image](https://github.com/surfbryce/beautiful-lyrics/assets/99515102/c0ee5f3d-7ea9-4127-9b01-ceca48f6fe5d)

**Comment by surfbryce** [comment] 2023-05-30 02:34
yep looks perfect, thank you! The issue is very clear now - I look for an "aside" element that has the aria-label "Now Playing View". The issue I did not take into account is that the text for that label changes based on the language - very very bad planning on my part.

Will get that fixed now! You should see the extension auto-update soon - thank you!

**Comment by magnusssz** [comment] 2023-05-30 02:36
thank you for your support! nice work <3

**Closed** 2023-05-30 02:43 UTC
