### ISSUE TITLE
latest update (on both spotify and  spicetify) and it doesn't show anything on the lyric menu

### ISSUE THREAD

**Issue by mezo7272** [surfbryce/beautiful-lyrics#417] opened 2024-04-22 21:33 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/79715642/25ade558-1e06-4755-b4a8-50f952212d8c)

**Comment by DerekFrostX** [comment] 2024-04-22 21:58
I've saw the same

**Comment by surfbryce** [comment] 2024-04-22 22:12
Duplicate of #340

**Closed by surfbryce** 2024-04-22 22:12 UTC
Labels: duplicate
