### ISSUE TITLE
Why aren´t working the lyrics display and the fullscreen? :c

### ISSUE THREAD

**Issue by heyyou34567** [surfbryce/beautiful-lyrics#424] opened 2024-04-23 23:20 UTC
![Captura de pantalla 2024-04-23 181914](https://github.com/surfbryce/beautiful-lyrics/assets/167933816/9fd89f0e-ca92-48bc-a258-6a26cf0559dc)

**Comment by surfbryce** [comment] 2024-04-23 23:38
Duplicate of #340

**Closed by surfbryce** 2024-04-23 23:38 UTC
Labels: duplicate
