### ISSUE TITLE
Up next banner 

### ISSUE THREAD

**Issue by itzreggie** [surfbryce/beautiful-lyrics#798] opened 2024-07-24 19:15 UTC
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

I saw another extension using it, but I prefer using Beautiful lyrics full screen mode.

### What is your Suggestion?

I want to see the upcoming song that will be playing when I am in full-screen mode. it could be placed at the top left side of the full-screen mode(cause the lyrics are on the right). It could only be displayed only when 80-90% of the song has played through.

![Screenshot 2024-07-24 220840](https://github.com/user-attachments/assets/f6cdea85-9ab2-4b52-a37e-1e12dfbcdfee)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment] 2024-07-27 16:21
@itzreggie Duplicate of #287

**Closed by surfbryce** 2024-07-27 16:21 UTC
Labels: Duplicate, Suggestion
