### ISSUE TITLE
MASSIVE GPU and Memory Usage on lyrics page

### ISSUE THREAD

**Issue by KK-Designs** [surfbryce/beautiful-lyrics#723] opened 2024-06-10 05:08 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

When opening the lyrics page, GPU utilization spikes to 100%, and memory doubles. Closing it does not fix the issue, only restarting the client does.

### What Country are you from?

United States

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.39.578.g0ea3f38b
Spotify Runtime: cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Spicetify Version: 2.36.12
Spicetify Theme: Better-Bloom / dark
Spicetify Extensions: [webnowplaying.js, fullAlbumDate.js, css-editor.js, imageOpener.js, playing-source.js, volumePercentage.js, fullScreenWrapper.js, spotifyGenres.js, extended-copy.js, CoverAmbience.js, beautiful-lyrics.mjs, theme.js]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

Console:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/71038229/95a4bed6-b0c1-4e70-816a-bfdb062e52d8)

Spotify HTML/CSS:
[Spotify.zip](https://github.com/user-attachments/files/15756691/Spotify.zip)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by KK-Designs** [comment] 2024-06-10 05:08
https://github.com/surfbryce/beautiful-lyrics/assets/71038229/a5f450f1-a668-475e-b9d9-789f0e49eda0

**Comment by surfbryce** [comment] 2024-06-10 05:52
@KK-Designs What are your specs? 100% GPU seems very odd, memory is to be expected, but GPU being 100% is interesting.

Which GPU is Spotify running on btw? It looks like it's running on GPU 0 so I'm assuming that is integrated graphics? If so that would make sense

This is potentially a duplicate of #185

**Comment by KK-Designs** [comment] 2024-06-10 06:28
> @KK-Designs What are your specs? 100% GPU seems very odd, memory is to be expected, but GPU being 100% is interesting.
> 
> Which GPU is Spotify running on btw? It looks like it's running on GPU 0 so I'm assuming that is integrated graphics? If so that would make sense
> 
> This is potentially a duplicate of #185 

It's running on a Intel UHD, a 4k 60hz capable iGPU. On the dedicated one, an RTX 2080 Super, uses about 40% of it, which is enough to lag some intense work I do. That's why i moved it the the GPU I don't care about (integrated)

**Comment by surfbryce** [comment] 2024-06-10 17:04
@KK-Designs I'll close this as a duplicate of #185 in this case, there are efforts being made to reduce performance degradation.

**Closed by surfbryce** 2024-06-10 17:04 UTC
Labels: Extension Bug, Duplicate
