### ISSUE TITLE
Theme Catppuccin (Mocha) issues

### ISSUE THREAD

**Issue by c0mplexx92** [surfbryce/beautiful-lyrics#420] opened 2024-04-23 11:55 UTC
Theme is Catppuccin specifically the Mocha version, lyric page wont display at all  
![image](https://github.com/surfbryce/beautiful-lyrics/assets/38200718/298f0053-d671-434a-96a5-bbb35f1edf72)

**Comment by surfbryce** [comment] 2024-04-23 18:43
Duplicate of #340

**Closed by surfbryce** 2024-04-23 18:43 UTC
Labels: duplicate
