### ISSUE TITLE
Wrong allignment in fullscreen mode 

### ISSUE THREAD

**Issue by RINxROZE** [surfbryce/beautiful-lyrics#941] opened 2024-10-25 12:51 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

![Lady Gaga - Die With A Smile 10_25_2024 7_08_23 PM](https://github.com/user-attachments/assets/52c85faa-9016-45a6-bc20-8c8c577e40f2)
wrong alignment please fix it, look like wired and QWP 

### What Country are you from?

Cambodia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: marketplace
Spicetify Extensions: [beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

[HTML.txt](https://github.com/user-attachments/files/17522248/HTML.txt)
[CSS.txt](https://github.com/user-attachments/files/17522258/CSS.txt)
![DevTools - xpui app spotify com_index html 10_25_2024 7_38_20 PM](https://github.com/user-attachments/assets/cae3653d-2329-4a67-81a6-3f4f40736a9d)
![DevTools - xpui app spotify com_index html 10_25_2024 7_38_31 PM](https://github.com/user-attachments/assets/1f47bdbb-9c29-4181-be13-6fa797b314f7)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Gmemster** [comment] 2024-10-26 06:19
Same issue here. The whole album panel is not working at all

**Comment by Anirbandasdev** [comment] 2024-10-26 18:07
#942

**Comment by sourya2007** [comment] 2024-10-27 04:34
i dont think that that is a bug the alignment is different because of the singer, when a song has more than two singers their respective parts are shown differently as in the alignment, in this case bruno mars has the right side and lady gaga has the left, correct me if i am wrong

**Comment by alessandrofoglia07** [comment] 2024-10-27 14:41
@sourya2007 the issue is the position of the cover art (should be centered, but it seems to be at the top of the window). by the way, I have the same issue

**Comment by GAMINGCHATS** [comment] 2024-10-27 16:39
Same issue here. And regarding what @sourya2007 said: it happens on songs that do have 2 singers and songs that have just 1 singer.

**Comment by jorge19832** [comment] 2024-10-27 16:43
![ds](https://github.com/user-attachments/assets/57933bff-89b3-4414-b5a9-4a52910c4a65)


> #942 Ya solucioné el problema, solo fusioné la solicitud de extracción @RINxROZE @surfbryce

Cómo?

**Comment by Anirbandasdev** [comment] 2024-10-27 19:34
> ![ds](https://github.com/user-attachments/assets/57933bff-89b3-4414-b5a9-4a52910c4a65)
> 
> 
> > #942 Ya solucioné el problema, solo fusioné la solicitud de extracción @RINxROZE @surfbryce
> 
> Cómo?


The admin not marge the code that why you see the alignment issue 😕

**Comment by Chaaps34** [comment] 2024-10-28 07:32
Can we have a video on how to fix this?

**Comment by 11even11** [comment] 2024-10-28 08:57
same issue 
![image](https://github.com/user-attachments/assets/67fe6ef6-88e4-4400-a8ea-e21aebe2c9b2)

**Comment by GAMINGCHATS** [comment] 2024-10-28 19:46
> Can we have a video on how to fix this?

@surfbryce (or anyone who has perms) hasn't merged the pull request which (according to other comments) has fixed this issue.

**Comment by jorge19832** [comment] 2024-10-28 20:06
> > ¿Podemos tener un vídeo sobre cómo solucionar esto?
> 
> @surfbryce(o cualquiera que tenga permisos) no ha fusionado la solicitud de extracción que (según otros comentarios) ha solucionado este problema.

What's that?

**Comment by GAMINGCHATS** [comment] 2024-10-28 20:09
> > > ¿Podemos tener un vídeo sobre cómo solucionar esto?
> > 
> > @surfbryce(o cualquiera que tenga permisos) no ha fusionado la solicitud de extracción que (según otros comentarios) ha solucionado este problema.
> 
> What's that?

A pull request is essentially an already fixed version of an app (or in this case extension) that to be implemented on the app/extension it has to be merged(added to the code) by an admin.

**Comment by jorge19832** [comment] 2024-10-28 20:14
> > > > ¿Podemos tener un vídeo sobre cómo solucionar esto?
> > > 
> > > 
> > > @surfbryce(o cualquiera que tenga permisos) no ha fusionado la solicitud de extracción que (según otros comentarios) ha solucionado este problema.
> > 
> > 
> > ¿Qué es eso?
> 
> Una solicitud de extracción es esencialmente una versión ya fija de una aplicación (o en este caso, una extensión) que, para implementarse en la aplicación/extensión, debe ser fusionada (agregada al código) por un administrador.

ohhhh thanks

**Comment by pivablonded** [comment] 2024-11-02 17:52
![Captura de pantalla (24)](https://github.com/user-attachments/assets/08108a59-4187-45e9-80c9-b80bec409433)
same issue, need help please

**Comment by Mysticc28** [comment] 2024-11-03 17:08
Hello there, there's a quick fix for the misoriented elements in the Beautiful Lyrics extension available thanks to @sanoojes

**Step 1 - Copy the below code** 
```typescript
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
    position: relative;
}
``` 
**Step 2 - Navigate to Spotify>Marketplace>Snippets**
![image](https://github.com/user-attachments/assets/2decf258-2f0e-4e65-985e-d5f2ac483a8b)

**Step 3 - Click the 'Add CSS' button in the bottom right corner**
![image](https://github.com/user-attachments/assets/3c156d43-7c5b-4956-8f97-ae4794aae606)

**Step 4 - Under Custom CSS, paste the code you just copied and add a Snippet name and description as you wish. Should look something like this so far.** 
![image](https://github.com/user-attachments/assets/9e29e9b9-4293-418e-8db7-a9d97c425a28)

**Step 5 - Hit Save CSS and done.** 
Your issue should be fixed but incase it isnt, refresh Spotify and check again. Once again, a big thanks to @sanoojes for the fix. Check out his themes, they're really cool. 

@RINxROZE @Gmemster @sourya2007 @alessandrofoglia07 @GAMINGCHATS @Chaaps34 @11even11 @Daniel23156 @xddK1ng @pivablonded here's the fix y'all

**Comment by GAMINGCHATS** [comment] 2024-11-03 17:10
Yay! Will test it prob tomorrow.

**Comment by pivablonded** [comment] 2024-11-04 16:09
How do I make it show the artist's album instead of the year?

**Closed** 2024-11-15 22:07 UTC
Labels: Extension Bug
