### ISSUE TITLE
FullScreen/Lyrics Page isn't working at all

### ISSUE THREAD

**Issue by l1kori** [surfbryce/beautiful-lyrics#448] opened 2024-04-29 13:28 UTC
### I've reinstalled Spotify and Spicetify several times (including with removing all of the Marketplace apps), but it didn't helped either.
![изображение_2024-04-29_232619907](https://github.com/surfbryce/beautiful-lyrics/assets/155972918/8d67faa5-98ec-4b0b-b0ab-2e2a3603e2d6)

**Comment by ishan-nagpure** [comment] 2024-04-29 14:35
yeah, same issue here...

**Comment by surfbryce** [comment] 2024-04-29 19:59
Duplicate of #441

**Closed by surfbryce** 2024-04-29 19:59 UTC
Labels: duplicate
