### ISSUE TITLE
Whole page taken up by album art blur

### ISSUE THREAD

**Issue by AriTheFirst** [surfbryce/beautiful-lyrics#541] opened 2024-05-17 05:50 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/134935244/61fed255-4484-45b8-827c-109afffd7c80)

Using the Catppuccin Mocha theme, and plugin installed manually from https://raw.githubusercontent.com/surfbryce/beautiful-lyrics/main/Builds/Release/beautiful-lyrics.mjs

**Comment by AriTheFirst** [comment] 2024-05-17 06:02
Update: Full updated spotify and spicetify and used the spicetify marketplace version, problem persists.

**Comment by KrazyTek** [comment] 2024-05-17 06:04
Installed automatically from Spicetify Marketplace 1.0.2, Windows 11, same issue

**Comment by AriTheFirst** [comment] 2024-05-17 06:10
I belive it's due to a recent update, as it was working on both of my computers as of 5/15 (see image below) and not it works on neither
![image](https://github.com/surfbryce/beautiful-lyrics/assets/134935244/77a58f5b-a252-4170-bcb4-05a282dabaca)

**Comment by luxluth** [comment] 2024-05-17 09:58
No theme plugin but have the same issue
![image](https://github.com/surfbryce/beautiful-lyrics/assets/74856540/356ed454-cf7e-4384-a3d8-d350c4e645f9)

**Comment by garryspins** [comment] 2024-05-17 11:46
Same issue ^

**Comment by bebrriko** [comment] 2024-05-17 12:02
Make sure to get all the latest versions of spotify and spicetify.
Make sure you have marketplace version of beautiful lyrics and you didn't download any from github manually. If you did then uninstall it.
Try to reinstall spotify fully.

**Comment by garryspins** [comment] 2024-05-17 15:21
Something broke the plugin, this is on their end.

**Comment by luxluth** [comment] 2024-05-17 15:25
> Make sure to get all the latest versions of spotify and spicetify. Make sure you have marketplace version of beautiful lyrics and you didn't download any from github manually. If you did then uninstall it. Try to reinstall spotify fully.

![2024-05-17-170720](https://github.com/surfbryce/beautiful-lyrics/assets/74856540/a8575494-cab8-4125-b58a-193a90f46df9)
nope

**Comment by vilewired** [comment] 2024-05-18 10:02
#539

**Comment by garryspins** [comment] 2024-05-18 12:37
Issue appears to be with the styling of `.lyrics-background-container`, Is fixed entirely by removing `position:absolute` and other sizing parameters.
![t](https://i.imgur.com/yRO3z8W.png)
![a](https://i.imgur.com/uY9YLWR.png)

**Comment by vilewired** [comment] 2024-05-18 16:00
You also need to disable height and overflow. Without overflow it's just a solid color, without height it's just the blur without the image / lyrics. Should look like this:
![image](https://cdn.vile.jp/img/20240518175617.png)
The check-boxes I have on can be disabled to look like the image @garryspins sent.
@surfbryce would you like to make this change to the css?

**Comment by Crxaw** [comment] 2024-05-18 17:43
Fixed by disabling global nav bar in experimental features. aka "Control" 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/48805031/8607a9c9-95f7-47d6-9223-ee8464cf5581)

**Comment by uricot** [comment] 2024-05-18 19:49
> Fixed by disabling global nav bar in experimental features. aka "Control" ![image](https://private-user-images.githubusercontent.com/48805031/331820391-8607a9c9-95f7-47d6-9223-ee8464cf5581.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjIwMzYsIm5iZiI6MTcxNjA2MTczNiwicGF0aCI6Ii80ODgwNTAzMS8zMzE4MjAzOTEtODYwN2E5YzktOTVmNy00N2Q2LTkyMjMtZWU4NDY0Y2Y1NTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE5NDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMzQ3ZDgwNzk3NTVmYzFhMGQ1ZDYwOGI3ZTgzNTI4MjQyNjMyNGYxMGQxYWFjOTIwYTcyM2E1YzExZTVhZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ruqwwlJtjD_4hRFUnDgRgmOGEy14GUwOPvL-lTL3388)

didnt fix it for me

**Comment by luxluth** [comment] 2024-05-18 19:51
Me neither

**Comment by MattiaPARRINELLO** [comment] 2024-05-18 21:31
Problem corrected for me.
Uninstall Beautiful Lyric from the marketplace, if beautiful lyrics is still here after a reload 
`spicetify config extension beautiful-lyrics.js-` 
`spicetify apply` 
to remove a manually installed Beautiful Lyrics if there is one.
Reinstall beautiful lyrics from the marketplace.

**Comment by surfbryce** [comment] 2024-05-18 21:35
Duplicate of #502

**Closed by surfbryce** 2024-05-18 21:35 UTC
Labels: duplicate

**Comment by garryspins** [comment] 2024-05-19 03:41
This is on windows. Reopen the issue.

**Comment by KrazyTek** [comment] 2024-05-19 04:00
Windows 11, version 23H2
Spicetify Marketplace 1.0.2
Beautiful Lyrics v3.3.1

No other themes or extensions were used, and experiments reset to default

**Comment by surfbryce** [comment] 2024-05-19 04:00
@garryspins It doesn't matter, I don't think you noticed but the OP is also running on Linux. Doesn't matter if its Windows, Linux, MacOS, or whatever, all that matters is that it is happening no matter the OS for *certain* people.

**Comment by surfbryce** [comment] 2024-05-19 04:03
@vilewired Your CSS changes are not an option because this doesn't work on every version of Spotify and only works for those affected, for everybody else NOT affected it will not look correct.

I am setting up a Wiki for certain things I need people to do when reporting bugs so that I can get more details about it. I don't have this issue and can't find out how to get it, so that's why there is no fix for this yet (or anything from me talking about it)

**Comment by AriTheFirst** [comment] 2024-05-19 04:07
Looking at your response in #502, you stated that you're removing support for older versions of spotify due to a change in the class structure, but is there any way you could release the legacy version of the plugin in javascript? It's just for the people who are stuck on older versions. Then people who need it can use the old code, and you can keep your focus on keeping the plugin up to date with the latest versions.

**Comment by vilewired** [comment] 2024-05-19 14:45
> @garryspins  @vilewired Your CSS changes are not an option because this doesn't work on every version of Spotify and only works for those affected, for everybody else NOT affected it will not look correct.
> 
> I am setting up a Wiki for certain things I need people to do when reporting bugs so that I can get more details about it. I don't have this issue and can't find out how to get it, so that's why there is no fix for this yet (or anything from me talking about it)

That's good. Basically I looked at a few things and Spotify for linux doesn't seem to get as many updates as Windows (I'm not complaining because Spotify actually works really well) so yeah the css classes will probably differ quite a bit. But the plugin also stopped working for my friend who uses the Windows version of it. I have to check what exactly his issue is (I manage all the spicetify stuff for him cause I'm more techy) because he also has some issues with the marketplace extension so it might be an outdated client on his side, I'll investigate further. What do you think about keeping 2 different branches, to release a Windows and a Linux version of the extension?

**Comment by garryspins** [comment] 2024-05-19 15:24
The problem does stem from an outdated version, having a legacy version/guide would be fantastic. Theres no reason this cant be done, it excludes soggfy users and people forced to use old versions.
