### ISSUE TITLE
Issue: Unable to use beautiful-lyrics. Theme Ziro Issues

### ISSUE THREAD

**Issue by fast-and-curious-1910** [surfbryce/beautiful-lyrics#203] opened 2023-12-02 15:54 UTC
I'm unable to even use it at all. Tried everything
![image](https://github.com/surfbryce/beautiful-lyrics/assets/64191803/0a5c067c-7bad-4d01-8a72-2121fe43516f)
Lyrics don't show up, at all. Not even at the little icon at the bottom 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/64191803/d60e2251-f48c-429e-a08f-3c0cec833036)
I absolutely love this extension but can't use it. :(

**Comment by surfbryce** [comment] 2023-12-06 21:14
Duplicate of #193

**Closed by surfbryce** 2023-12-06 21:14 UTC
Labels: duplicate
