### ISSUE TITLE
Lyrics and Fullscreen display are Blank

### ISSUE THREAD

**Issue by CHILLxGAME** [surfbryce/beautiful-lyrics#438] opened 2024-04-26 18:19 UTC
![Screenshot 2024-04-26 234556](https://github.com/surfbryce/beautiful-lyrics/assets/168223981/7a0481b2-aac0-46e8-b3e0-32b8c7c7f708)

**Comment by HimmlischesIQ** [comment] 2024-04-26 18:49
![grafik](https://github.com/surfbryce/beautiful-lyrics/assets/143601078/16a6753e-eb13-421d-b719-de578ee9d0c5)
Same Problem here, with theme and without.
Spotify für Windows (64 Bit)
1.2.35.663.gb699649e
Spicetify v2.36.8

**Comment by surfbryce** [comment] 2024-04-26 19:19
Duplicate of #340

**Closed by surfbryce** 2024-04-26 19:19 UTC
Labels: duplicate
