### ISSUE TITLE
Full Screen and Lyrics page don't show up.

### ISSUE THREAD

**Issue by aroralucifer** [surfbryce/beautiful-lyrics#485] opened 2024-05-10 20:43 UTC
Side Lyrics bar on Now Playing Works great but when I click the lyrics page or the full screen button. It doesn't happen. The middle of the screen blanks.
![Screenshot (1)](https://github.com/surfbryce/beautiful-lyrics/assets/86018874/068f4ded-eadf-409b-bbb6-e59ecd0d4a4c)

**Comment by surfbryce** [comment] 2024-05-10 20:45
Duplicate of #441

**Closed by surfbryce** 2024-05-10 20:45 UTC
Labels: duplicate
