### ISSUE TITLE
lyrics resync only when clicking on them

### ISSUE THREAD

**Issue by dxcvvxd** [surfbryce/beautiful-lyrics#324] opened 2024-03-18 19:33 UTC
i have this issue where the lyrics are offset by about a second or two untill i click on them to make the song jump to that lyric and it becomes synced
is there a way to make it sync automatically?

**Comment by dxcvvxd** [comment] 2024-03-19 15:40
1. i think it should but it doesnt and hasnt been for basically forever since i've installed this extension
2. this happens on every song that doesnt have these very advanced lyrics (idk how to describe them, ill just attach some screenshots)
"normal" lyrics (they are desynced):
![image](https://github.com/surfbryce/beautiful-lyrics/assets/77129815/e8a97f97-d1c8-4b4a-8965-2f2680bf354b)
"advanced" lyrics:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/77129815/6f40ffcd-7a28-4587-923c-9a7d2fde1f3f)
3. yes this does happen when i restart spotify

i can also record a few videos showcasing it if you need

**Comment by surfbryce** [comment] 2024-03-19 18:33
@dxcvvxd It'd be helpful if you provided the song names, there's a potential that the lyrics retrieved aren't for the right version/duration of the song. I'll have to see if it's happening for me or if I can replicate it in some way, since otherwise, there won't be any way for me to verify what the problem is

**Comment by dxcvvxd** [comment] 2024-03-31 14:52
ok, after a while i've managed to figure out why that happens
so if you have auto crossfade enabled, the lyrics become desynced when the song loops around by that time that you've set in crossfade.

so now here is my question: is this fixable? because im myself a type of person to listen to a track over and over untill it becomes boring and if it has lyrics, then it kinda becomes an issue.

**Comment by surfbryce** [comment] 2024-05-15 17:27
Should be fixed due to a rewrite of the Player module

**Closed by surfbryce** 2024-05-15 17:27 UTC
Labels: bug
