### ISSUE TITLE
Lyrics cut off in Hindi Language

### ISSUE THREAD

**Issue by GODDASUR** [surfbryce/beautiful-lyrics#272] opened 2024-02-06 10:20 UTC
https://github.com/surfbryce/beautiful-lyrics/assets/100470960/8cf6f1b0-32f6-4c31-8eda-d9d894ccb6de

**Comment by surfbryce** [comment] 2024-02-16 12:44
Duplicate of #250

**Closed by surfbryce** 2024-02-16 12:44 UTC
Labels: duplicate
