### ISSUE TITLE
beautiful lyrics full page not working

### ISSUE THREAD

**Issue by krishna-0811** [surfbryce/beautiful-lyrics#391] opened 2024-04-13 16:40 UTC
extension is for spicetify named "Beautiful lyrics". Whenever i click on full page it is not showing anything but the small side tab is working fine as well as i reinstalled my spotify but still not working. The spotify and spicetify are both of latest version. Please help with this problem cause i use it everyday as it is so good and gives a nice look.
![Screenshot 2024-04-13 220036](https://github.com/surfbryce/beautiful-lyrics/assets/166940771/ac073687-275d-4f51-ad5c-03878fc2e1f3)

**Comment by surfbryce** [comment] 2024-04-13 16:46
Duplicate of #340

**Closed by surfbryce** 2024-04-13 16:46 UTC
Labels: duplicate
