### ISSUE TITLE
beautiful lyrics extension is not working

### ISSUE THREAD

**Issue by Nar0** [surfbryce/beautiful-lyrics#357] opened 2024-04-06 06:24 UTC
issue with Beautiful-Lyrics, there is something strange with this extension, usually the lyrics can be seen directly in playing view, this doesn't appear and if you press the beautiful lyrics icon, there is only a black screen and nothing is displayed
![Screenshot 2024-04-06 132347](https://github.com/surfbryce/beautiful-lyrics/assets/115962054/a7f3153c-2ceb-4988-9e1b-568384687e86)

**Comment by ismetpiuv** [comment] 2024-04-06 07:54
I have the same issue i think they are gonna fix it soon.

**Comment by Euro-pol** [comment] 2024-04-06 10:45
same for me

**Comment by Euro-pol** [comment] 2024-04-06 10:46
probably is duplicate of #340

**Comment by surfbryce** [comment] 2024-04-06 14:13
Duplicate of #340

**Closed by surfbryce** 2024-04-06 14:13 UTC
Labels: duplicate

**Comment by Nar0** [comment] 2024-04-07 04:52
> probably is duplicate of #340

how to fix it?
