### ISSUE TITLE
Bugged full screen display 

### ISSUE THREAD

**Issue by MumboJoebo** [surfbryce/beautiful-lyrics#644] opened 2024-05-27 18:02 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/109863751/ffe4c0fa-e127-4090-b659-a308714e32ff)

**Comment by surfbryce** [comment] 2024-05-27 18:04
@MumboJoebo Duplicate of many existing issues, will be fixed in the next patch

**Closed by surfbryce** 2024-05-27 18:04 UTC

**Comment by MumboJoebo** [comment] 2024-05-27 20:03
do you have an et on next patch
