### ISSUE TITLE
Lyrics don't sync when connecting to another device via Spotify Connect

### ISSUE THREAD

**Issue by fastnlight0** [surfbryce/beautiful-lyrics#638] opened 2024-05-26 18:23 UTC
## Spotify info
```
Spotify for macOS (Apple Silicon)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11
```
Country: US
Console:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/77035115/0eca5f67-2035-4a48-91dd-ffac0093da3f)
HTML and CSS files:
[Spotify HTML and CSS.zip](https://github.com/surfbryce/beautiful-lyrics/files/15448486/Spotify.HTML.and.CSS.zip)

## Issue information

When playing music on another device via [Spotify Connect](https://support.spotify.com/us/article/spotify-connect/), the lyrics are at a standstill and do not sync:
![Screenshot 2024-05-26 at 1 18 43 PM](https://github.com/surfbryce/beautiful-lyrics/assets/77035115/f0818d23-9ee7-451b-be4f-175f73e8a670)
When switching back to the computer itself, the lyrics return to being synced. When switching back to the Spotify Connect device, the lyrics go back to the beginning and remain unsynced.

**Comment by surfbryce** [comment] 2024-05-27 06:10
@fastnlight0 Duplicate of #531

**Closed by surfbryce** 2024-05-27 06:10 UTC
Labels: Duplicate
