### ISSUE TITLE
Sidebar lyrics seems not appear correctly

### ISSUE THREAD

**Issue by kinoko117** [surfbryce/beautiful-lyrics#574] opened 2024-05-19 11:57 UTC
https://github.com/surfbryce/beautiful-lyrics/assets/100466609/a04e5cbe-7344-4851-a62f-3a95fab937c3

Tried to re-install, still the same .

**Comment by lefretti** [comment] 2024-05-19 12:41
Same issue here! The pretty background is back and the lyrics are pretty but theyre not synced!

**Comment by surfbryce** [comment] 2024-05-19 23:23
Duplicate of #526

**Closed by surfbryce** 2024-05-19 23:23 UTC
Labels: duplicate
