### ISSUE TITLE
Lyrics only appear in small form on the right

### ISSUE THREAD

**Issue by ahmet972772** [surfbryce/beautiful-lyrics#497] opened 2024-05-15 20:54 UTC
I enabled the plugin but I can't enlarge the lyrics
![image](https://github.com/surfbryce/beautiful-lyrics/assets/159818977/0465c93c-8bb5-4f89-9c71-7a14661587c0)

**Comment by ziIIas** [comment] 2024-05-15 20:56
wait one minute   Bro there is an update coming out  in literally   5 minutes

**Comment by Blankk02** [comment] 2024-05-15 21:09
> wait one minute Bro there is an update coming out in literally 5 minutes

![image](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/f3c036d4-9016-4266-95f4-e22e31f1aed0)
hmm

**Comment by jeremybosma** [comment] 2024-05-15 21:21
https://github.com/surfbryce/beautiful-lyrics/issues/441

40 more minutes i believe

**Comment by surfbryce** [comment] 2024-05-15 21:22
Duplicate of #441

**Closed by surfbryce** 2024-05-15 21:22 UTC
Labels: duplicate
