### ISSUE TITLE
lyrics not working i guess -->(using the marketplace version)<--

### ISSUE THREAD

**Issue by EternalArmies** [surfbryce/beautiful-lyrics#407] opened 2024-04-18 01:20 UTC
when i click the lyrics icon ( the mic with the tiny stars around it) it just shows a blank screen, no lyrics no nothing.

**Comment by Ruken16** [comment] 2024-04-18 06:33
me too

**Comment by surfbryce** [comment] 2024-04-18 06:35
Duplicate of #340

**Closed by surfbryce** 2024-04-18 06:35 UTC
Labels: duplicate
