### ISSUE TITLE
[Suggestion] Compatibility with Romanized Lyrics extension

### ISSUE THREAD

**Issue by maxed3** [surfbryce/beautiful-lyrics#144] opened 2023-09-14 20:09 UTC
My suggestion is to make this extension compatible with the Romanized lyrics extension as I prefer looking at romanized lyrics.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/145064483/1166d752-ff0d-4df5-9a8f-2dabb9bd2ac3)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/145064483/b5f67f21-2201-490b-afb0-12675d53311d)

**Comment by surfbryce** [comment] 2023-09-14 20:58
Duplicate of #51

**Closed by surfbryce** 2023-09-14 20:58 UTC
