### ISSUE TITLE
lyrics page and full page display dont work

### ISSUE THREAD

**Issue by SimaoGT11** [surfbryce/beautiful-lyrics#459] opened 2024-05-03 15:40 UTC
my lyrics page and full app display dont work and the card where the small lyrics appear dont have the colours of the album cover. i dont know why this happened,but when i first installed this, it was working very well, but now i can only see the lyrics in the card on the right and without the colours. someone could help me pls, I already installed and unistalled spotify and spicitify and everything. i just dont know what to do
![Captura de ecrã 2024-05-03 164032](https://github.com/surfbryce/beautiful-lyrics/assets/168848572/28b4b37b-b686-4565-8c13-66d8edcf7401)

**Comment by arya070104** [comment] 2024-05-03 15:43
bro go to #441 
you will know all problems

**Comment by surfbryce** [comment] 2024-05-03 17:43
Duplicate of #441

**Closed by surfbryce** 2024-05-03 17:43 UTC
Labels: duplicate

**Comment by SimaoGT11** [comment] 2024-05-05 17:00
> bro go to #441 you will know all problems

So that means that they are working on resolving that problem? Im not a very good english speaker
