### ISSUE TITLE
Beautiful Lyrics is laggy

### ISSUE THREAD

**Issue by ralee0110** [surfbryce/beautiful-lyrics#199] opened 2023-11-18 00:34 UTC
a week ago everything was fine with the extension, after a couple of days I noticed that my extension was lagging a lot and it started to annoy me... is there any fix ?

**Comment by ragh111** [comment] 2023-12-02 15:25
It's so laggy! I can't even enjoy my songs
:<<... how can it be fixed?

**Comment by surfbryce** [comment] 2023-12-06 21:07
Duplicate of #185

**Closed by surfbryce** 2023-12-06 21:07 UTC
Labels: duplicate

**Comment by bhxp** [comment] 2024-06-07 21:11
recently started getting this issue, why is it?
