### ISSUE TITLE
Lyrics still not loading

### ISSUE THREAD

**Issue by Kouki002** [surfbryce/beautiful-lyrics#653] opened 2024-05-29 06:45 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Now Ariana Grandes's Song Lyrics Also Not Loading Its Used To Be But Not Now !!
![spoti](https://github.com/surfbryce/beautiful-lyrics/assets/170322028/90a22bee-fe14-42d2-a012-b6bb536e3c24)

### What Country are you from?

India

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spicetify V2.36.11

### Spotify HTML/CSS and Console Screenshots

![dev](https://github.com/surfbryce/beautiful-lyrics/assets/170322028/1e09563a-b2be-4490-983c-d3b0118f972a)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment] 2024-05-29 06:46
@Kouki002 Duplicate of existing issues, also sorry that you weren't able to follow the shortcuts, that is meant for when the patch comes out which is soon.

**Closed by surfbryce** 2024-05-29 06:46 UTC
Labels: Extension Bug

**Comment by Kouki002** [comment] 2024-05-29 06:49
SO Its Solved IN Next Patch That's What You Trying to Say ???
