### ISSUE TITLE
doesnt appear for me

### ISSUE THREAD

**Issue by Golonchy** [surfbryce/beautiful-lyrics#430] opened 2024-04-25 06:55 UTC
first of all, thank you for this plugin, its very epic.
im on the latest version of spicetify but beautiful lyrics wont appear for me, any fix?
https://streamable.com/87jv0u
im asking you this bcs before i knew it was broken but now i see that you updated the plugin 6 days ago so it might be a bug
<img width="201" alt="Screenshot 2024-04-25 at 09 54 15" src="https://github.com/surfbryce/beautiful-lyrics/assets/165617563/9c7923c9-f2be-4377-bd47-225c983168cb">

**Comment by surfbryce** [comment] 2024-04-25 06:57
Duplicate of #340, and no, I did not update it recently, any activity on the GitHub counts as being "updated" on the Spicetify Marketplace unfortunately

**Closed by surfbryce** 2024-04-25 06:57 UTC
Labels: duplicate

**Comment by Golonchy** [comment] 2024-04-25 18:05
o ok, sorry for bothering you
have a good rest of your day!
