### ISSUE TITLE
Flat background colour on Now Playing view

### ISSUE THREAD

**Issue by lefretti** [surfbryce/beautiful-lyrics#414] opened 2024-04-21 11:31 UTC
This is probably the least serious problem compared to the other bugs with Beautiful Lyrics that people have been posting but i've started having the now playing view more because of the extension since its nice to look at because of the blurred, moving background. Pretty sure this came at the same time as the lyrics page being completely blank-issue. I put the way it looks like now first and the way it looked before at the bottom.
![Näyttökuva (450)](https://github.com/surfbryce/beautiful-lyrics/assets/128063727/1adbff12-6941-446a-8aa7-792eb0c85fa0)
![Näyttökuva (431)](https://github.com/surfbryce/beautiful-lyrics/assets/128063727/0ba8534c-3d7c-477d-8323-900d027afcd4)

**Comment by surfbryce** [comment] 2024-04-21 11:34
Duplicate of #340

**Closed by surfbryce** 2024-04-21 11:34 UTC
Labels: duplicate
