### ISSUE TITLE
Bug with full screen lyrics

### ISSUE THREAD

**Issue by MumboJoebo** [surfbryce/beautiful-lyrics#470] opened 2024-05-06 13:23 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/109863751/d4814e54-e215-41db-a30e-fffe2c35ccd1)
sometimes the lyrics pop up but sometimes they dont and the cover album is half of the screen with the controls

**Comment by surfbryce** [comment] 2024-05-06 14:35
Duplicate of #441

**Closed by surfbryce** 2024-05-06 14:35 UTC
Labels: duplicate
