### ISSUE TITLE
Theme dribbblish/catppuccin-frappe issues

### ISSUE THREAD

**Issue by CharlesNewsom** [surfbryce/beautiful-lyrics#362] opened 2024-04-06 22:07 UTC
Beautiful lyrics renders a basic screen, without lyrics.

![Spotify_uG33zRB190](https://github.com/surfbryce/beautiful-lyrics/assets/142063597/5fed87ce-c5c4-494a-820e-5dca689d416d)

**Comment by DerHK** [comment] 2024-04-06 22:12
The author has to update the extention. The last update was in February. Just wait it will get updated eventually.

**Comment by CharlesNewsom** [comment] 2024-04-06 22:27
> ### THE EXTENTION IS NOT UP TO DATE WITH LATEST SPOTIFY VERSION.
> 
> Just wait and spicetify should automatically update the extention.

Ahhhhh, okay. Thank you for the response man <3

**Comment by surfbryce** [comment] 2024-04-06 23:24
Duplicate of #340

**Closed by surfbryce** 2024-04-06 23:24 UTC
Labels: duplicate
