### ISSUE TITLE
Theme HAZY Issues

### ISSUE THREAD

**Issue by PrometheusPy** [surfbryce/beautiful-lyrics#490] opened 2024-05-13 19:13 UTC
Using HAZY, lyrics do not show up at all
![Screenshot (305)](https://github.com/surfbryce/beautiful-lyrics/assets/91027598/11642172-2242-4d0c-a9b8-2861a2fe527c)

**Comment by surfbryce** [comment] 2024-05-13 19:53
Duplicate of #441

**Closed by surfbryce** 2024-05-13 19:53 UTC
Labels: duplicate
