### ISSUE TITLE
Bad FPS

### ISSUE THREAD

**Issue by pheological** [surfbryce/beautiful-lyrics#554] opened 2024-05-17 20:45 UTC
before, when i used beautifulLyrics, the fps was fine, and it worked fine. Now, when i use it, its so delayed and the fps is like 2. I have an m1 macbook air, so i dont think its a performance issue.

**Comment by pheological** [comment] 2024-05-17 20:46
also, this issue only applies to fullscreen mode, when its small, it works fine.

**Comment by surfbryce** [comment] 2024-05-18 21:29
Duplicate of existing performance issues

**Closed by surfbryce** 2024-05-18 21:29 UTC
Labels: duplicate
