### ISSUE TITLE
The fullscreen is bugged out

### ISSUE THREAD

**Issue by Johnnu123** [surfbryce/beautiful-lyrics#954] opened 2024-10-31 08:07 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

![image_2024-10-31_190304463](https://github.com/user-attachments/assets/184fa3ed-ff29-45e5-9df7-2ec2d26cccce)

The fullscreen is out of place, the lyrics work fine tho.

### What Country are you from?

Australia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: Bloom / comfy
Spicetify Extensions: [shuffle+.s, shuffle+.js, beautiful-lyrics.mjs, theme.js]
Spicetify Custom Apps: [marketplace, lyrics-plus]

### Spotify HTML/CSS and Console Screenshots

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: Bloom / comfy
Spicetify Extensions: [shuffle+.s, shuffle+.js, beautiful-lyrics.mjs, theme.js]
Spicetify Custom Apps: [marketplace, lyrics-plus]

Spotify Version: 1.2.49.439.gfae492c7
Spotify Runtime: cef_129.0.11+g57354b8+chromium-129.0.6668.90
Spicetify Version: 2.38.4
Spicetify Theme: Bloom / comfy
Spicetify Extensions: [shuffle+.s, shuffle+.js, beautiful-lyrics.mjs, theme.js]
Spicetify Custom Apps: [marketplace, lyrics-plus]

![image_2024-10-31_190642703](https://github.com/user-attachments/assets/950e93f5-d0e6-4a7e-a132-703dd4998e4e)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by bblackbro** [comment] 2024-11-02 04:54
do u find a way to fix it?

**Comment by batt1111** [comment] 2024-11-02 05:25
so how to fix this problem in an easy way ?

**Comment by violetto-rose** [comment] 2024-11-02 08:04
Also the volume bar knob is out of place

**Comment by PirimTanrisi** [comment] 2024-11-02 11:42
need a fix on this now. also FEAR. and DAMN. is goated man good taste

**Comment by HVT123123** [comment] 2024-11-02 11:45
so we all got the same problem but is it because of our device or the extension got bugged?

**Comment by PirimTanrisi** [comment] 2024-11-02 15:26
> so we all got the same problem but is it because of our device or the extension got bugged?

i think its the plugin

**Comment by Mysticc28** [comment] 2024-11-03 06:15
> so we all got the same problem but is it because of our device or the extension got bugged?
> 

There's just 2 lines of code that are causing the extension to bug out. There's a fix uploaded under the pull request but the developer hasn't merged it yet.

**Comment by PirimTanrisi** [comment] 2024-11-03 06:57
> > so we all got the same problem but is it because of our device or the extension got bugged?
> 
> There's just 2 lines of code that are causing the extension to bug out. There's a fix uploaded under the pull request but the developer hasn't merged it yet.

can you tell me where it is please (if i can fix it myself??)

**Comment by sanoojes** [comment] 2024-11-03 09:44
Please review this CSS snippet; I'm unsure of its accuracy But it works. @surfbryce 

```css
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
    position: relative;
}
```

**Comment by leafymar** [comment] 2024-11-03 10:44
> Please review this CSS snippet; I'm unsure of its accuracy But it works. @surfbryce
> 
> ```css
> .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
> .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
>     position: relative;
> }
> ```


hello how do i install this fix?

**Comment by Mysticc28** [comment] 2024-11-03 17:14
Hello there, there's a quick fix for the misoriented elements in the Beautiful Lyrics extension available thanks to @sanoojes

**Step 1 - Copy the below code** 
```typescript
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
    position: relative;
}
``` 
**Step 2 - Navigate to Spotify>Marketplace>Snippets**
![image](https://github.com/user-attachments/assets/2decf258-2f0e-4e65-985e-d5f2ac483a8b)

**Step 3 - Click the 'Add CSS' button in the bottom right corner**
![image](https://github.com/user-attachments/assets/3c156d43-7c5b-4956-8f97-ae4794aae606)

**Step 4 - Under Custom CSS, paste the code you just copied and add a Snippet name and description as you wish. Should look something like this so far.** 
![image](https://github.com/user-attachments/assets/9e29e9b9-4293-418e-8db7-a9d97c425a28)

**Step 5 - Hit Save CSS and done.** 
Your issue should be fixed but incase it isnt, refresh Spotify and check again. Once again, a big thanks to @sanoojes for the fix. Check out his themes, they're really cool. 

@Johnnu123 @Kaysil @bblackbro @violetto-rose @PirimTanrisi @HVT123123 here's the fix y'all

**Comment by sanoojes** [comment] 2024-11-03 22:46
Duplicate of https://github.com/surfbryce/beautiful-lyrics/issues/954

**Closed** 2024-11-15 22:05 UTC
Labels: Extension Bug
