### ISSUE TITLE
[Bug]: Blank canvas instead of lyrics

### ISSUE THREAD

**Issue by ItsGarek** [surfbryce/beautiful-lyrics#649] opened 2024-05-28 10:59 UTC
### Bug Report Checklist

- [X] **If you are making a Bug Report about the Extension being broken in some way, read this**: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#there-is-something-wrong-with-the-extension-not-lyrics
- [X] **If you are making a Bug Report about Lyrics in some way, read this**: https://github.com/surfbryce/beautiful-lyrics/wiki/Making-a-Bug-Report#song-lyrics-are-missing-are-incorrect-or-arent-the-best-synced-version

### What happened?

https://github.com/surfbryce/beautiful-lyrics/assets/52253795/de7aa224-7b82-4a07-8221-7c49104f826a

### The country you are from

Poland

### Spotify/Spicetify Version

2.36.11

### What os are you seeing the problem on?

Windows

### Screenshot of the entire Console

![Spotify_jkhUfqBcuW](https://github.com/surfbryce/beautiful-lyrics/assets/52253795/e3622b11-f06f-41bd-9055-5e831905b154)

**Comment by bSkySoft** [comment] 2024-05-28 13:20
Just reinstall spicetify following: https://spicetify.app/docs/advanced-usage/uninstallation/
Fixed it when i had this problem.

**Comment by Joeeeeb5** [comment] 2024-05-28 16:55
Yep, same issue.

**Comment by surfbryce** [comment] 2024-05-28 18:35
@ItsGarek Duplicate of existing issues, will be fixed in the next patch

**Closed by surfbryce** 2024-05-28 18:35 UTC
Labels: Extension Bug, Duplicate

**Comment by ItsGarek** [comment] 2024-05-29 07:16
Thanks fellas! Looking forward to trying the new version
