### ISSUE TITLE
Lyrics Page not working

### ISSUE THREAD

**Issue by JeannasBro** [surfbryce/beautiful-lyrics#425] opened 2024-04-23 23:44 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/59500634/33fbd018-0f43-4d51-b29b-475dd4f54b8c)

The lyrics are working in the card but not the lyrics page, where its just blank.
I'm using the comfy theme

**Comment by BariIsStupid** [comment] 2024-04-23 23:56
duplicate of #340

**Comment by surfbryce** [comment] 2024-04-24 00:00
Duplicate of #340

**Closed by surfbryce** 2024-04-24 00:00 UTC
Labels: duplicate
