### ISSUE TITLE
Beautiful Lyrics not working

### ISSUE THREAD

**Issue by xitsjulix** [surfbryce/beautiful-lyrics#398] opened 2024-04-14 18:13 UTC
- When I klick on the microphone/lyrics symbol with the stars, I get a grey screen without lyrics. On the other symbol I just get the default spotify one.
- Full Screen also not working.
- I re installed Spotify (website edition) and Spicetify.
- This is with every kind of music (korean, english, german, japanese,... 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/167024263/a710c953-effa-4a68-babf-4c99ef96fbc3)

**Comment by surfbryce** [comment] 2024-04-14 18:51
Duplicate of #340

**Closed by surfbryce** 2024-04-14 18:51 UTC
Labels: duplicate
