### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by EvilMortyyyy** [surfbryce/beautiful-lyrics#487] opened 2024-05-11 14:46 UTC
I reinstall, update, etc and the lyrics not found
<img width="955" alt="Sin título" src="https://github.com/surfbryce/beautiful-lyrics/assets/169542353/5c3d92be-b99f-4ca9-9514-a9fc9d7ff953">

**Comment by wangpengcBob** [comment] 2024-05-11 14:51
same issue, this happened about 1 month ago, tried reinstall spotify, spicetify, this extension for several times but still not working till now. Both Windows and macOS.

**Comment by wangpengcBob** [comment] 2024-05-11 14:54
please refer to #410 and #340

**Comment by nhth31** [comment] 2024-05-11 14:55
duplicate of #441

**Comment by surfbryce** [comment] 2024-05-11 17:07
Duplicate of #441

**Closed by surfbryce** 2024-05-11 17:07 UTC
Labels: duplicate
