### ISSUE TITLE
Background not working

### ISSUE THREAD

**Issue by wthcxrtii** [surfbryce/beautiful-lyrics#379] opened 2024-04-10 13:50 UTC
The background of the mod is not working, i tried to reset spotify and doesn't work too 
![imagen_2024-04-10_094952584](https://github.com/surfbryce/beautiful-lyrics/assets/166626650/9a8a78c1-41ed-4d31-8fe8-133a5d3cc9df)

**Comment by surfbryce** [comment] 2024-04-10 17:18
Duplicate of #340

**Closed by surfbryce** 2024-04-10 17:18 UTC
Labels: duplicate
