### ISSUE TITLE
Lyrics arn't clipping on Romanization

### ISSUE THREAD

**Issue by PIndividual** [surfbryce/beautiful-lyrics#747] opened 2024-06-21 10:29 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Sometimes, when Romanization is enabled on Chinese songs, they don't get clipped right so that part of the Romanization is hidden and can't be seen, this often happens when Spotify isn't in fullscreen.
<img width="980" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/62368342/60019093-5ba3-4f39-873c-04cafe5268d5">

### What Country are you from?

China

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.39.578.g0ea3f38b
Spotify Runtime: cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Spicetify Version: 2.36.13
Spicetify Theme: Hazy / Base
Spicetify Extensions: [fullAlbumDate.js, volumePercentageWrapper.js, romaja_lyrics.js, group-session.js, immersiveView.js, scannables.js, spotifyGenres.js, QueueTime.js, songstats.js, beautiful-lyrics.mjs, theme.js]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

[HTML & CSS.zip](https://github.com/user-attachments/files/15926313/HTML.CSS.zip)
<img width="1280" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/62368342/d607e67f-9d5b-4f91-a38e-654c77317906">
<img width="1280" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/62368342/8e2a20fe-5d52-4a93-8e4c-59543d1c41d2">

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment] 2024-06-21 17:27
@PIndividual Duplicate of #161

**Closed by surfbryce** 2024-06-21 17:27 UTC
Labels: Extension Bug, Duplicate
