### ISSUE TITLE
the extention not showing in full screen

### ISSUE THREAD

**Issue by hiso0ka44** [surfbryce/beautiful-lyrics#367] opened 2024-04-08 00:00 UTC
![Screenshot 2024-04-08 015521](https://github.com/surfbryce/beautiful-lyrics/assets/107445490/b522c2a5-b2f8-44f1-8d64-f78f9c266d73)
the extention disable fullscreen and make only is showing in the side panel not the main one

**Comment by surfbryce** [comment] 2024-04-08 01:09
Duplicate of #340

**Closed by surfbryce** 2024-04-08 01:09 UTC
Labels: duplicate
