### ISSUE TITLE
Suggestion: beautiful-lyrics inspired background theme

### ISSUE THREAD

**Issue by DeveloLongScript** [surfbryce/beautiful-lyrics#489] opened 2024-05-12 21:41 UTC
What if there was a theme, similar to something like [Hazy (a spicetify theme)](https://github.com/Astromations/Hazy), but with the gradient component of beautiful lyrics as the background. I feel like something like that would be really cool as a theme, because Hazy's gradient, well, isn't the best.

Thanks! :D

**Comment by surfbryce** [comment] 2024-05-13 01:51
Duplicate of #37

**Closed by surfbryce** 2024-05-13 01:51 UTC
Labels: duplicate
