### ISSUE TITLE
full screen problem

### ISSUE THREAD

**Issue by SenpaiNeedsHelp** [surfbryce/beautiful-lyrics#452] opened 2024-05-01 08:49 UTC
![Spotify Free 5_1_2024 1_32_39 PM](https://github.com/surfbryce/beautiful-lyrics/assets/117751391/0371e509-4960-493e-8ac3-461e4a0f76da)
 
the lyrics shows up in the side view but when i click on full screen its just blank.
i have tried reinstalling everything but its still not working.

**Comment by Anonoymity** [comment] 2024-05-01 10:03
Update will be out in 24 hours. This is an issue for the newer version of spotify. You can download an old version if you want an early fix tho

**Comment by surfbryce** [comment] 2024-05-01 17:28
Duplicate of #441

**Closed by surfbryce** 2024-05-01 17:28 UTC
Labels: duplicate
