### ISSUE TITLE
Fullscreen is completly messed up

### ISSUE THREAD

**Issue by LoganWolfie** [surfbryce/beautiful-lyrics#322] opened 2024-03-17 02:58 UTC
On my horizontal monitor it's better but still ui overlapping over eachother. My vertical monitor on the other hand is completely messed up. I only keep my spotify on my vertical monitor so it sucks not having it work. 

I deleted every mod I had including my theme and that was not the issue. 

![image](https://github.com/surfbryce/beautiful-lyrics/assets/72407034/0dc00a06-4611-497d-864b-ade23549aa28)

**Comment by LoganWolfie** [comment] 2024-03-17 03:09
Also while in fullscreen this side bar is not scrolling up in sync with the lyrics.

The lyrics show up a few bars after. 
<img width="186" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/72407034/8c2ffb87-d72c-4c08-858c-2879331ba518">

**Comment by surfbryce** [comment] 2024-03-18 00:27
Duplicate of #76

**Closed by surfbryce** 2024-03-18 00:27 UTC
Labels: duplicate
