### ISSUE TITLE
Extension Not Showing

### ISSUE THREAD

**Issue by ssamu11** [surfbryce/beautiful-lyrics#714] opened 2024-06-07 14:02 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Extension not showing on my spotify

### What Country are you from?

Indonesia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify for Windows (64 bit)
1.2.39.578.g0ea3f38b
Spicetify v2.36.12

### Spotify HTML/CSS and Console Screenshots

-

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment] 2024-06-07 16:33
@ssamu11 Going to say this is a duplicate of #705

**Closed by surfbryce** 2024-06-07 16:33 UTC
Labels: Extension Bug, Duplicate
