### ISSUE TITLE
Beautiful Lyrics stopped working.

### ISSUE THREAD

**Issue by PramisPJ** [surfbryce/beautiful-lyrics#375] opened 2024-04-09 21:23 UTC
I was having some issues with Spicetify so I re-downloaded and set up Spicetify again, since then Beautiful Lyrics has stopped working and shows a blank screen which used to work before although other extensions still work fine. I also have reinstalled it 2-3 times again and set it up for it to still not work. If any help is possible I would appreciate it. P.S. Just in case this info helps, my normal lyrics have not been working for a long time before even downloading Spicetify although pop-up lyrics work fine.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/166559849/b086e75c-7682-4654-bcf0-eda60f2b4f06) - Beautiful Lyrics.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/166559849/e7ebe20d-bcee-4355-85be-588656490e2c) - Default lyrics.

**Comment by PramisPJ** [comment] 2024-04-09 21:26
Also, the show lyrics button doesn't do anything and it is not there anymore.

**Comment by PramisPJ** [comment] 2024-04-09 21:53
Also, the show lyrics button does work but when I try to go into full display mode it doesn't work and stays in the corner it only shows up sometimes and not always so not reliable.

**Comment by surfbryce** [comment] 2024-04-09 22:30
Duplicate of #340

**Closed by surfbryce** 2024-04-09 22:30 UTC
Labels: duplicate
