### ISSUE TITLE
my background is not changing it is only static colour picture

### ISSUE THREAD

**Issue by DarkKnight45** [surfbryce/beautiful-lyrics#418] opened 2024-04-23 07:17 UTC
![Screenshot (24)](https://github.com/surfbryce/beautiful-lyrics/assets/98516085/fb3929b0-75d8-432f-9ea8-5cf6f1894e2a)

**Comment by surfbryce** [comment] 2024-04-23 18:44
Duplicate of #340

**Closed by surfbryce** 2024-04-23 18:44 UTC
Labels: duplicate
