### ISSUE TITLE
Lyrics Lagging

### ISSUE THREAD

**Issue by GriddyYet** [surfbryce/beautiful-lyrics#734] opened 2024-06-16 09:03 UTC
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

This may not be a suggestion, but I would like to point out that the add-on is lagging on my device...
ASUS G533ZX

### What is your Suggestion?

Laggy :(

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by LazerSkar** [comment] 2024-06-17 22:40
Sometimes the mod is laggy for whatever reason, could be background, but sometimes its cpu intensive too. just, take for granted its a mod within an app.
anyway what i would say is update spicetify and try reinstall the mod see if that fixes it
update with powershell and do 
`spicetify update`

**Comment by LazerSkar** [comment] 2024-06-17 22:41
i had lag before an a restart of my pc (not just spotify had problems that time) and that fixed it for my 2070s and r5 5600g pc

**Comment by surfbryce** [comment] 2024-06-19 18:43
Duplicate of #185

**Closed by surfbryce** 2024-06-19 18:43 UTC
Labels: Duplicate, Suggestion
