### ISSUE TITLE
doesnt work on 1.2.25.2011

### ISSUE THREAD

**Issue by sou0npercs** [surfbryce/beautiful-lyrics#209] opened 2023-12-06 19:32 UTC
i tried updating and reinstalling and this worked on this theme before the update

**Comment by MoonVxbesZ** [comment] 2023-12-06 20:13
Same here

**Comment by BurnMyName** [comment] 2023-12-06 20:18
I thought only I was having this issue. Here, too, the button is missing.

**Comment by Eingla** [comment] 2023-12-06 20:52
I think they removed it, I saw that they did the latest update today.

**Comment by surfbryce** [comment] 2023-12-06 20:54
I haven't removed anything and the update I made wasn't an update. I made some commits to GitHub; when an update is made you will see it in the Releases section.

I'm working on a lot of things at the moment, so I will take a look at everything breaking today and fix that.

**Comment by Eingla** [comment] 2023-12-06 20:55
d
![Uploading Screenshot 2023-12-06 215356.png…]()
o you also see the lyrics as black like this?

**Comment by Eingla** [comment] 2023-12-06 20:56
ok everything understood, thanks

**Comment by surfbryce** [comment] 2023-12-06 21:00
also duplicate of #208

**Closed by surfbryce** 2023-12-06 21:00 UTC
