### ISSUE TITLE
Lyrics Page's button on top are not working

### ISSUE THREAD

**Issue by kutawhat** [surfbryce/beautiful-lyrics#197] opened 2023-11-14 18:51 UTC
These buttons disappears right when I hover on them
![Снимок экрана 2023-11-14 в 21 48](https://github.com/surfbryce/beautiful-lyrics/assets/64655969/d4b9cb74-507b-4628-826b-05e731f670ef)

**Comment by surfbryce** [comment] 2023-11-15 04:29
Duplicate of #186

**Closed by surfbryce** 2023-11-15 04:29 UTC
Labels: duplicate

**Comment by Samplayz2007** [comment] 2023-11-30 11:38
issue still persist
