### ISSUE TITLE
Fullscreen & Cinema on small vertical display is broken

### ISSUE THREAD

**Issue by Janamen** [surfbryce/beautiful-lyrics#316] opened 2024-03-11 01:20 UTC
When using a vertical monitor (1100x3840), the entire display breaks and slowly scrolls down in cinema mode, hide player mode doesn't work, it only gets a little more transparent. 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/88746002/059b5525-4b56-48b1-b4ff-8340fbcaf090)
In fullscreen its the same, also broken and the lyrics are half offscreen, the album covers everything 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/88746002/40925e5d-c5a5-433a-b728-4f6a29e7b5fa)

Spotify for Windows (32 bit)
1.2.26.1187.g36b715a1
Spicetify v2.33.2
Theme: Default Dynamic / Base
Extensions: songstats.js, beautiful-lyrics.js, fullScreenWrapper.js, playEnhancedSongs.js, playlist-icons.js, romaja_lyrics.js, loopyLoop.js, immersiveView.js, shuffle+.js, fullAppDisplay.js, romaji_lyrics.js, popupLyrics.js, quickQueue.js, quick-add-to-playlist.js, noControls.js, discography-to-playlist.js, default-dynamic.js, Vibrant.min.js
Custom apps: marketplace, lyrics-plus, new-releases

**Comment by surfbryce** [comment] 2024-03-11 04:45
Duplicate of #76

**Closed by surfbryce** 2024-03-11 04:45 UTC
Labels: duplicate
