### ISSUE TITLE
Small text cutoff in fullscreen

### ISSUE THREAD

**Issue by swiffyjk** [surfbryce/beautiful-lyrics#142] opened 2023-09-10 09:43 UTC
For some songs, the glow around the text and sometimes the text itself is cut off on the left side when in fullscreen.
Correct-looking lyrics:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/80045453/25e5fe1d-8939-4bdd-8e22-820d35578623)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/80045453/ebb00686-81ef-4890-aa43-3bbdca56436d)
Cut-off lyrics:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/80045453/ee123803-5232-4c5a-9bc9-73b817b6a1b0)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/80045453/9f1507f1-7883-46ec-a11b-0671deee37fa)
This doesn't happen in Cinema Mode, the lyrics sidebar or the standard lyrics page. Only fullscreen mode.

**Comment by surfbryce** [comment] 2023-09-10 17:08
Duplicate of #100

**Closed by surfbryce** 2023-09-10 17:08 UTC
Labels: duplicate
