### ISSUE TITLE
Full Screen Bugged

### ISSUE THREAD

**Issue by RocraftGamerYT** [surfbryce/beautiful-lyrics#444] opened 2024-04-28 15:41 UTC
https://github.com/surfbryce/beautiful-lyrics/assets/79378601/ab6f8887-498b-4f64-a764-0f7d46ad855c

**Comment by borxxo** [comment] 2024-04-28 16:20
i have the same problem

**Comment by J-from-Nucleon** [comment] 2024-04-28 16:21
Known issue
Refer #441

**Comment by surfbryce** [comment] 2024-04-28 20:08
Duplicate of #441

**Closed by surfbryce** 2024-04-28 20:08 UTC
Labels: duplicate

**Comment by RocraftGamerYT** [comment] 2024-04-29 14:22
@surfbryce so, its gonna get fixed this month?
