### ISSUE TITLE
showing a blank screen in beautiful lyric section

### ISSUE THREAD

**Issue by udaykesariHp** [surfbryce/beautiful-lyrics#451] opened 2024-05-01 04:23 UTC
brother why can i see the songs lyric in the beautiful section am waiting for update from past 1 month and please fix this issue in window, Am both linux and windows user in linux its working perfectly fine but in windows is bugged

https://github.com/surfbryce/beautiful-lyrics/assets/154318396/0af16c1a-4efe-4a67-98ad-7f748aaff74b

**Comment by surfbryce** [comment] 2024-05-01 04:53
Duplicate of #441

**Closed by surfbryce** 2024-05-01 04:53 UTC
Labels: duplicate
