### ISSUE TITLE
spicetify update new verstion,This ex not work

### ISSUE THREAD

**Issue by westjing** [surfbryce/beautiful-lyrics#478] opened 2024-05-09 09:48 UTC
Reinstall spotify and spicetify,but it not work

**Comment by boochySans** [comment] 2024-05-09 10:14
#411

**Comment by boochySans** [comment] 2024-05-09 10:16
Wait no #441

**Comment by surfbryce** [comment] 2024-05-09 16:34
Duplicate of #441

**Closed by surfbryce** 2024-05-09 16:34 UTC
Labels: duplicate
