### ISSUE TITLE
Fullscreen Bug

### ISSUE THREAD

**Issue by Mak37512** [surfbryce/beautiful-lyrics#318] opened 2024-03-11 12:06 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/65138813/6ae25190-2531-4155-b738-5c866953d983)
The "Add to playlist" icon climbs onto the text. No themes have been installed.

**Comment by surfbryce** [comment] 2024-03-11 20:31
Duplicate of #231

**Closed by surfbryce** 2024-03-11 20:31 UTC
Labels: duplicate
