### ISSUE TITLE
Full screen not working

### ISSUE THREAD

**Issue by joicelss** [surfbryce/beautiful-lyrics#403] opened 2024-04-16 20:18 UTC
when i press the full screen button it just shows as blank there isnt anything
![Näyttökuva 2024-04-16 231835](https://github.com/surfbryce/beautiful-lyrics/assets/167249819/298fb2c4-d05a-4fec-a282-0d2fa5719993)

**Comment by bharataddagatla** [comment] 2024-04-16 20:26
I am facing the same problem too,

**Comment by surfbryce** [comment] 2024-04-16 21:40
Duplicate of #340

**Closed by surfbryce** 2024-04-16 21:40 UTC
Labels: duplicate
