### ISSUE TITLE
Cinema View not covering top and bottom bars / Unexpected behavior when artists names exceed available space

### ISSUE THREAD

**Issue by magnusssz** [surfbryce/beautiful-lyrics#639] opened 2024-05-26 19:04 UTC
Spotify para Windows (64 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11
Brazil

![image](https://github.com/surfbryce/beautiful-lyrics/assets/99515102/53938b8f-1b62-4380-b263-fdcfca04febf)

as you can see in the screenshot, spotify bottom and top bars keep showing when in cinema view. after updating spotify, this seems to happen only in my 5:4 1280x1024 monitor.

there is another bug shown in the same screenshot where each of the artists names individually move left at different speeds when there's no space to show them all, instead of the entire line of text moving together, causing them to cluster and move on top of each other.

**Comment by surfbryce** [comment] 2024-05-27 06:11
@magnusssz  Duplicate of #56

**Closed by surfbryce** 2024-05-27 06:11 UTC
Labels: Duplicate
