### ISSUE TITLE
When playing on a connected device, beautiful-lyrics won't auto-scroll the lyrics

### ISSUE THREAD

**Issue by LightningReflex** [surfbryce/beautiful-lyrics#599] opened 2024-05-21 14:18 UTC
Whenever you play a song from another device, the lyrics won't auto-scroll/show where it currently is on a different device running beautiful-lyrics.

When running normally:
![(21-05-24 16;14) 5327 Spotify  gE0o9](https://github.com/surfbryce/beautiful-lyrics/assets/59992415/54331800-5b4f-4ae4-a33d-080a57769428)

When playing on another device:
![(21-05-24 16;21) 5328 Spotify  EzmOn](https://github.com/surfbryce/beautiful-lyrics/assets/59992415/933cbcfe-b91e-4f8a-81da-0711216eb0c1)

**Comment by Alehaaaa** [comment] 2024-05-21 15:36
Duplicate of #531

**Comment by surfbryce** [comment] 2024-05-21 19:32
Duplicate of #531

**Closed by surfbryce** 2024-05-21 19:32 UTC
Labels: Duplicate
