### ISSUE TITLE
Dynamic background toggle

### ISSUE THREAD

**Issue by toothmickel** [surfbryce/beautiful-lyrics#893] opened 2024-09-16 23:52 UTC
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

Sometimes its hard to read the lyrics with the background being a similar colour to the lyrics, or the dynamic background is sometimes just a harsh colour.

### What is your Suggestion?

I suggest possibly a button somewhere or a config option to turn the dynamic background on and off to a colour that contrasts with the lyrics.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment] 2024-09-22 01:06
@toothmickel Duplicate of #157

**Closed by surfbryce** 2024-09-22 01:06 UTC
Labels: Duplicate, Suggestion
