### ISSUE TITLE
beautiful lyrics only showing on the sidebar

### ISSUE THREAD

**Issue by goodguymiso** [surfbryce/beautiful-lyrics#475] opened 2024-05-08 14:33 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/74549201/3c5c6945-6032-4991-9841-77c982d03d18)

**Comment by cuxtiie** [comment] 2024-05-08 14:36
same here as well!! they wont show anywhere but the sidebar.
off topic but what theme are you using? its pretty!

**Comment by enzon19** [comment] 2024-05-08 14:49
https://github.com/surfbryce/beautiful-lyrics/issues/441

**Comment by surfbryce** [comment] 2024-05-08 18:36
Duplicate of #441

**Closed by surfbryce** 2024-05-08 18:36 UTC
Labels: duplicate

**Comment by goodguymiso** [comment] 2024-05-08 19:28
> same here as well!! they wont show anywhere but the sidebar. off topic but what theme are you using? its pretty!

its called hazy, it adds the album cover art to ur background but if ur talking about the album art its summer salt my favorite band :))
