### ISSUE TITLE
I click the Beautiful lyrics and everything turns grey

### ISSUE THREAD

**Issue by dysterus** [surfbryce/beautiful-lyrics#353] opened 2024-04-05 17:02 UTC
I click the beautiful lyrics button and everything turns grey. This happened randomly beacsue I did not add or remove any extensions and I do not have any themes.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/166157553/6852ba61-1878-4ee5-9a14-53c87d4351fc)

**Comment by dysterus** [comment] 2024-04-05 17:27
Btw i have reinstalled spicetify and the beautiful lyrics extension as well

**Comment by crispim6aL** [comment] 2024-04-05 17:36
man, i got the same issue... idk why

**Comment by arya070104** [comment] 2024-04-05 17:36
Same bro i am also facing that same problem.

**Comment by arya070104** [comment] 2024-04-05 17:38
![Screenshot 2024-04-05 230754](https://github.com/surfbryce/beautiful-lyrics/assets/166160461/d07f393e-9efd-4e96-b3c8-97e60cb99551)

**Comment by bunnyboyshawn** [comment] 2024-04-05 18:39
Same for me!! Needs an update immediately :((

**Comment by surfbryce** [comment] 2024-04-05 18:45
Duplicate of #340

**Closed by surfbryce** 2024-04-05 18:45 UTC
Labels: duplicate
