### ISSUE TITLE
Add Option to Toggle “Dynamic Background” for Sidebar

### ISSUE THREAD

**Issue by zero-mindset** [surfbryce/beautiful-lyrics#718] opened 2024-06-09 03:41 UTC
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

I found the visuals in the sidebar to be a bit much at times and distracting

### What is your Suggestion?

Hi, I love everything about the beautiful-lyrics extension except the busy sidebar dynamic background. I was hoping an option to toggle it on and off could be added. Thanks!

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment] 2024-06-09 05:08
@zero-mindset Duplicate of #157

**Closed by surfbryce** 2024-06-09 05:08 UTC
Labels: Duplicate, Suggestion
