### ISSUE TITLE
Lyrics Aren't showing and Takes the whole screen

### ISSUE THREAD

**Issue by Drakon2424** [surfbryce/beautiful-lyrics#607] opened 2024-05-22 04:00 UTC
This is my screen when  i try to open up the lyrics: 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/66153476/a32aea78-c6d1-426c-89cd-c805a2c1b00b)

And when i close them, and open up the info bar this happens: 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/66153476/f8f88556-1db4-4c66-b025-64de7ca69d99)

I've uninstalled spicetify, uninstalled the lyrics extension, installed it, did it like 5 times, nothing changes, help?

**Comment by bebrriko** [comment] 2024-05-22 04:10
Maybe its because of the theme?

**Comment by Jukehere** [comment] 2024-05-22 04:56
Its not because of the theme, I have the same issue with stock. Had to delete the plugin

**Comment by surfbryce** [comment] 2024-05-22 05:50
Duplicate of #590 and #603

**Closed by surfbryce** 2024-05-22 05:50 UTC
Labels: Duplicate
