### ISSUE TITLE
Beautiful lyrics not working?

### ISSUE THREAD

**Issue by retrobase** [surfbryce/beautiful-lyrics#95] opened 2023-08-05 04:35 UTC
<img width="1728" alt="Screenshot 2023-08-04 at 11 32 13 PM" src="https://github.com/surfbryce/beautiful-lyrics/assets/141250727/0796a406-802e-43c8-bfc9-1a03487c7a21">
<img width="1728" alt="Screenshot 2023-08-04 at 11 32 57 PM" src="https://github.com/surfbryce/beautiful-lyrics/assets/141250727/0def0cb6-b430-4536-9d73-07125c100713">
<img width="476" alt="Screenshot 2023-08-04 at 11 34 58 PM" src="https://github.com/surfbryce/beautiful-lyrics/assets/141250727/200d74e0-3899-47cb-93da-b5422eb8d7d6">

I've restarted, deleted Spotify/Spicetify multiple times.

**Comment by McYeetusTM** [comment] 2023-08-05 04:40
was just about to put this, Im new but I've tried everything in FAQ even downloading locally and nothing works.

**Comment by surfbryce** [comment] 2023-08-05 04:46
@McYeetusTM @retrobase This is due to some weird conflict between the last and current update. I am working on it. You should see an update come out that *should* fix it

**Comment by surfbryce** [comment] 2023-08-05 04:51
@McYeetusTM @retrobase If you restart Spotify it should work now

**Comment by McYeetusTM** [comment] 2023-08-05 05:01
@surfbryce Idk if this is from the extension but i get an error "Error parsing markdown (HTTP 403)"

**Comment by surfbryce** [comment] 2023-08-05 05:07
@McYeetusTM If you could provide a screenshot of the error (or the whole console) that would be lovely

**Comment by McYeetusTM** [comment] 2023-08-05 05:20
I dont know if this is Spicetify or what
https://github.com/surfbryce/beautiful-lyrics/assets/141472902/98cb9097-b978-4c08-8640-dcf6b4779781

**Comment by surfbryce** [comment] 2023-08-05 05:21
@McYeetusTM Yeah that is Spicetify. Markdown is what is used to display the information page for extensions

**Comment by McYeetusTM** [comment] 2023-08-05 05:22
@surfbryce Should I reinstall Spicetify?

**Comment by McYeetusTM** [comment] 2023-08-05 05:23
Now it works all of a sudden, I am confused

**Comment by surfbryce** [comment] 2023-08-05 05:24
@McYeetusTM I just want to know for the most part - is Beautiful Lyrics working for you now?

**Comment by McYeetusTM** [comment] 2023-08-05 05:25
@surfbryce just installed it and no, its not, but the other guy might have to tell you too in case its just me

**Comment by surfbryce** [comment] 2023-08-05 05:28
@McYeetusTM Would you mind screenshotting the Spotify console to help me?

To do that you need to run "spicetify apply enable-devtools" and then right click on any empty space that doesn't trigger the Spotify menu. Once you do that click "Developer Tools" and go to the console tab and screenshot everything there.

Thanks!

**Comment by McYeetusTM** [comment] 2023-08-05 05:33
![image_2023-08-05_003327263](https://github.com/surfbryce/beautiful-lyrics/assets/141472902/cdbe417e-ed67-43fe-98ed-f04a85f71c27)

**Comment by surfbryce** [comment] 2023-08-05 05:43
@McYeetusTM 
<img width="1563" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/261a7203-daf0-4463-9c86-1124ef238d36">
Well this seems to be the issue here.

Not for sure what could cause this though so we need to do another search. Could you go to the Network tab and scroll through everything there to see if you can find a request like this:
<img width="213" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/0556dde2-eb32-44d6-befb-0e1dc02e91d0">

More importantly look for any failed requests (ones in red), those would like this:
<img width="215" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/995dbad7-67ab-41bd-9d35-12fb21cd9cf5">

However, you'll need to reload Spotify to get an accurate reading of this. Not restart btw - so to reload right click in an empty space again and click Reload. This will keep the Developer Tools open and allow us to find out whats failing here specifically.

Once you've done that then you can do what I stated above. Once you find one that matches what I was describing click on it and it should look like this:
<img width="772" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/119c19db-70e8-4329-9f09-2460e7952533">

Screenshot that view AND click on the "Response" sub-tab and screenshot that as well.

I really appreciate you helping - it's very possible this is a Spicetify issue. The reason I say this is because they switched to a different domain to get extensions (jsdelivr.xyz instead of jsdelivr.net). The issue is that the .xyz version doesn't work for everyone for some reason. So this error might be from that directly.

**Comment by McYeetusTM** [comment] 2023-08-05 06:05
is this it?
![image_2023-08-05_010450775](https://github.com/surfbryce/beautiful-lyrics/assets/141472902/d666b95e-d0ab-4e8a-a6a5-c3b2ef19cf8d)
![image_2023-08-05_010517453](https://github.com/surfbryce/beautiful-lyrics/assets/141472902/86ee19e3-218d-4b35-9ea2-49e2234eb2cd)

**Comment by surfbryce** [comment] 2023-08-05 06:07
@McYeetusTM Yep that's it! PERFECT!

Alright so unfortunate news is that this is not an issue with the extension but an issue with Spicetify. I already explained the issue but a quick recap is that they changed the ending domain (from .net to .xyz) to make it so people in Egypt (and in places where the .net domain doesn't work) can use Marketplace extensions. However this caused it to break for certain people.

Can you try going to: https://cdn.jsdelivr.xyz/gh/surfbryce/beautiful-lyrics@main/dist/beautiful-lyrics.js?time=1691215419499

and seeing what it does in a regular browser? Screenshot the result if you can.

**Comment by McYeetusTM** [comment] 2023-08-05 06:10
![image_2023-08-05_011019662](https://github.com/surfbryce/beautiful-lyrics/assets/141472902/54b2f6ba-353f-4861-8d30-2143fc329e87)

**Comment by surfbryce** [comment] 2023-08-05 06:11
@McYeetusTM Yep unfortunately this will be a Spicetify problem. They are aware and actually have made changes in their codebase to fix this once and for all for everybody but you'll have to wait until they push that update out. That update should be pushed out today or tomorrow.

**Comment by McYeetusTM** [comment] 2023-08-05 06:12
@surfbryce Alright, thanks for letting me know, I'll keep myself updated with spicetify

**Comment by surfbryce** [comment] 2023-08-06 09:19
@retrobase Since McYeetus' problem is not like yours. I'm going to close this and mark this as a duplicate and move it to #89. I think I know exactly why and how to fix this.

**Closed by surfbryce** 2023-08-06 09:19 UTC
