### ISSUE TITLE
Lyrics not showing up (Feb 15, 2024)

### ISSUE THREAD

**Issue by Memberite** [surfbryce/beautiful-lyrics#286] opened 2024-02-16 00:19 UTC
The lyrics fail to show up, only leaving the animated background. No themes are installed, I tried all of the methods listed in the instructions.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/92491712/959113af-434f-4248-8543-db4cb96b0ad5)

**Comment by surfbryce** [comment] 2024-02-16 12:18
Duplicate of #240

**Closed by surfbryce** 2024-02-16 12:18 UTC
Labels: duplicate
