### ISSUE TITLE
It autoplays on spotify startup

### ISSUE THREAD

**Issue by Black-Speedy** [surfbryce/beautiful-lyrics#138] opened 2023-09-06 18:07 UTC
I don't know why if it is intended or not, but it instantly starts playing a song whenever I have this extension installed, but stops as soon as I uninstall it

**Comment by surfbryce** [comment] 2023-09-06 18:26
Duplicate of #127, I am aware of this and working on it.

**Closed by surfbryce** 2023-09-06 18:26 UTC
