### ISSUE TITLE
The lyrics move out at different resolutions

### ISSUE THREAD

**Issue by 311time** [surfbryce/beautiful-lyrics#627] opened 2024-05-25 13:50 UTC
When you resize the spotify window or open it in full screen on a lower resolution than main monitor, the beginning of the first line moves out (up or down)
2k - 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/78899658/a4fc8adf-0972-4ffb-81a6-f71fe11b1543)
fhd - 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/78899658/b32a66d1-69fa-44f9-8eb2-88652bc9ce13)
Custom sizes - 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/78899658/54a99fe8-d3ad-4ddb-a457-24204e4be0f7)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/78899658/d8800148-3ad4-4aeb-ac95-d319b15a26cc)

**Comment by bleghj** [comment] 2024-05-25 15:59
they look the same

**Comment by 311time** [comment] 2024-05-25 16:06
The place above the line changes, the lyrics move up or down
In the third screenshot, an entire line is missing because of this

**Comment by surfbryce** [comment] 2024-05-27 06:09
@311time Duplicate of #531 (related, not exactly the same, but related bug)

**Closed by surfbryce** 2024-05-27 06:09 UTC
