### ISSUE TITLE
Lyrics Not Showing

### ISSUE THREAD

**Issue by hysterCAL** [surfbryce/beautiful-lyrics#280] opened 2024-02-14 21:53 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/160075720/1bca87cc-d167-4380-a3bb-203a9e0ca11f)
Hello, this just randomly happened, it was working before but randomly just stopped and now it doesnt show the lyrics.

**Comment by asdfcx2345** [comment] 2024-02-15 01:59
yeah same thing happened to me

**Comment by Stew4theWin** [comment] 2024-02-15 04:17
same with me

**Comment by LisuxOG** [comment] 2024-02-15 04:45
It's happening to me in almost all the songs

**Comment by wmgaertner** [comment] 2024-02-15 23:14
Did you update the spotify client? According to [spicetify](https://github.com/spicetify/spicetify-cli/releases/tag/v2.31.3), with v1.2.31 of the client, Spotify has changed a function that seems to impact lyric extensions.

**Comment by surfbryce** [comment] 2024-02-16 12:16
Duplicate of #240

**Closed by surfbryce** 2024-02-16 12:16 UTC
Labels: duplicate
