### ISSUE TITLE
Fullscreen mode in veritical monitors can't reach to the bottom. 

### ISSUE THREAD

**Issue by oneeyedreaper** [surfbryce/beautiful-lyrics#137] opened 2023-09-06 09:42 UTC
When the fullscreen mode is triggered, the effect does not cover some parts at the bottom.
Screenshots for reference
![image](https://github.com/surfbryce/beautiful-lyrics/assets/53879034/3fdd88d9-6f08-4b2f-aea7-5cc7b7b97cd6) 
With Dribbblish theme
![image](https://github.com/surfbryce/beautiful-lyrics/assets/53879034/4dcb5255-34b9-454e-93f7-b3d7b1a3bad1) 
With Default theme
I'm using a 16:9 monitor in portrait mode and the latest spicetify and beautiful-lyrics versions.
I'm not sure if this is an issue only on my device or an actual bug.

**Comment by surfbryce** [comment] 2023-09-06 18:25
Duplicate of #76, read up there and you'll find where this bug is currently at.

**Closed by surfbryce** 2023-09-06 18:25 UTC
