### ISSUE TITLE
Lyric provider?

### ISSUE THREAD

**Issue by LeviSnoot** [surfbryce/beautiful-lyrics#293] opened 2024-02-20 10:45 UTC
I've quickly looked over the code but I'm not sure who the lyrics provider is, especially for synced lyrics. I assume there's multiple, which fall back to each other if one isn't available. From `src/Services/Player/Song.ts` it looks like Spotify (Musixmatch) itself is one of them and there's a reference to `beautiful-lyrics.socalifornian.live`. That's about as much as I can gather on my own.

It would be useful to have this information so I know where to contribute/correct lyrics and syncs.

**Comment by JxseDelRey** [comment] 2024-02-20 18:13
![image](https://github.com/surfbryce/beautiful-lyrics/assets/153209219/f28e14ee-7f65-4708-b1f3-2cd13dd6a6d6)



me pasa esto

**Comment by froyo4u** [comment] 2024-02-20 20:53
#291

**Comment by mkrychtalek** [comment] 2024-02-20 22:42
You can contribute on [Musixmatch](https://www.musixmatch.com/sign-up), that’s the fastest way (for me). Though, that does not make the lyrics word-by-word even with them being synced in the app. I would like to know what provider is it, if it’s not transcribed by backend.

**Comment by mkrychtalek** [comment] 2024-02-20 22:43
> #291

That did not help me, personally. Just some random chit-chat, but I didn’t understand the ending and the point of the question.

**Comment by surfbryce** [comment] 2024-02-21 02:26
Duplicate of #93 and #158

**Closed by surfbryce** 2024-02-21 02:26 UTC
Labels: duplicate
