### ISSUE TITLE
Blank page every time playing songs from artist page (SpotX+Spicetify)

### ISSUE THREAD

**Issue by naufaldori** [surfbryce/beautiful-lyrics#844] opened 2024-08-17 15:27 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

1. Install SpotX Install_New_Theme.bat, podcast on, block update off
2. Open and login to spotify, after 30 seconds close spotify again
3. Install spicetify with default cli parameter `iwr -useb https://raw.githubusercontent.com/spicetify/cli/main/install.ps1 | iex`
4. Install marketplace when prompted
5. Open spotify, open marketplace, install Beautiful Lyrics
6. open any artist page, click on a song to play
7. **Blank page**
8. Restore page by clicking 3 dots on the top left -> help -> troubleshooting -> reload

### What Country are you from?

Indonesia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.44.405.g81fd6352
Spotify Runtime: cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Spicetify Version: 2.37.1
Spicetify Theme: marketplace
Spicetify Extensions: [beautiful-lyrics.mjs]
Spicetify Custom Apps: [marketplace]

### Spotify HTML/CSS and Console Screenshots

![Screenshot (641)](https://github.com/user-attachments/assets/d2bc6386-d888-4e59-ba9c-e3f7eb313972)
[Spotify css.txt](https://github.com/user-attachments/files/16645404/Spotify.css.txt)
[Spotify html.txt](https://github.com/user-attachments/files/16645405/Spotify.html.txt)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment] 2024-08-17 21:32
@naufaldori Duplicate of #821

**Closed by surfbryce** 2024-08-17 21:32 UTC
Labels: Extension Bug, Duplicate
