### ISSUE TITLE
Lyrics Not Visible

### ISSUE THREAD

**Issue by DasteXd** [surfbryce/beautiful-lyrics#413] opened 2024-04-20 20:22 UTC
Fresh install of Spotify from Spotify website and fresh install of Spicetify twice.
I only downloaded the lyrics plugin and nothing else, the first time I put a theme to see if it worked but it still didn't and the second time I reinstalled everything with just the lyrics plugin and I don't see anything, it's like I didn't have it downloaded, the full screen mode doesn't even work, it had the Addblock so I removed it to see if that was the reason but it still doesn't work for me.
Free/non-premium account.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/86079955/4b370153-2ccd-4e0a-abf0-b00569ad6f74)

**Comment by surfbryce** [comment] 2024-04-20 20:51
Duplicate of #340

**Closed by surfbryce** 2024-04-20 20:51 UTC
Labels: duplicate
