### ISSUE TITLE
You can see the buttons if you zoom too much

### ISSUE THREAD

**Issue by iPixelGalaxy** [surfbryce/beautiful-lyrics#837] opened 2024-08-14 02:55 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

Not a major issue but I did figure I would throw it in here in case you wanted perfection. :)

### What Country are you from?

Canada

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify for Windows (64 bit)
1.2.44.405.g81fd6352
Spicetify v2.37.1

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/user-attachments/assets/9cb7bc05-5e47-4d11-96cb-10edd3aee972)
[Spotify.css.txt](https://github.com/user-attachments/files/16607154/Spotify.
[Spotify.html.txt](https://github.com/user-attachments/files/16607155/Spotify.html.txt)
css.txt)

(you can't upload .html or .css file raw for some reason on github)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment] 2024-08-17 20:55
@iPixelGalaxy This is a duplicate of #56 (it is the same issue basically, and you can achieve the same effect on normal resolutions without a zoom in)

**Closed by surfbryce** 2024-08-17 20:55 UTC
Labels: Extension Bug, Duplicate
