### ISSUE TITLE
none of the lyrics are showing up 

### ISSUE THREAD

**Issue by raef10** [surfbryce/beautiful-lyrics#402] opened 2024-04-15 22:15 UTC
so i do all thing typing here and nothing chance 
![image_2024-04-16_011452382](https://github.com/surfbryce/beautiful-lyrics/assets/167141862/a1d9249a-1063-4f16-84c3-9c86d10ac494)
![image_2024-04-16_011503175](https://github.com/surfbryce/beautiful-lyrics/assets/167141862/64b6bbd3-145e-458b-b809-57364e545b04)
 
 sorry for my bad en

**Comment by surfbryce** [comment] 2024-04-15 22:16
Duplicate of #340

**Closed by surfbryce** 2024-04-15 22:16 UTC
Labels: duplicate
