### ISSUE TITLE
lyrics not showing in full screen 

### ISSUE THREAD

**Issue by Aditya708907** [surfbryce/beautiful-lyrics#400] opened 2024-04-15 04:11 UTC
![Screenshot (5)](https://github.com/surfbryce/beautiful-lyrics/assets/153764311/2cb7fa43-55ab-4c51-9b2c-0972619fedab)

take a look at the screenshot.

**Comment by surfbryce** [comment] 2024-04-15 04:13
Duplicate of #340

**Closed by surfbryce** 2024-04-15 04:13 UTC
Labels: duplicate
