### ISSUE TITLE
Few visual bugs regarding the fullscreen view

### ISSUE THREAD

**Issue by Protaro6789** [surfbryce/beautiful-lyrics#249] opened 2024-01-16 03:19 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/115462607/55797220-a2d9-435a-8340-8af14dae2cd2)
It seems like if a song has been added to your playlist, the green tick looks off. Hope to see this fixed soon :)

**Comment by surfbryce** [comment] 2024-02-16 12:33
Duplicate of #231

**Closed** 2024-03-01 05:06 UTC
Labels: duplicate
