### ISSUE TITLE
Fullscreen Issue

### ISSUE THREAD

**Issue by Devin21h** [surfbryce/beautiful-lyrics#399] opened 2024-04-14 20:49 UTC
I just have a black screen when I want to enter the fullscreen mode.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/159663309/54b7d77b-cb8a-40ea-8e11-55b80a1445fe)

**Comment by Devin21h** [comment] 2024-04-14 20:51
I also tried to reinstall Spotify (from the official web page) and Spicetify but it doesn´t helped me at all.

**Comment by NoahDuong** [comment] 2024-04-14 21:45
I'm having the same issue and kept wondering if it's just me who has this bug.
The lyrics are still okay if I kept it running on side bar tho.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/117856578/7d309c8d-961d-4ff1-ae73-df1bfae3c74e)

**Comment by GoncaloSilva25** [comment] 2024-04-14 23:42
I also have the same problem

**Comment by surfbryce** [comment] 2024-04-15 02:38
Duplicate of #340

**Closed by surfbryce** 2024-04-15 02:38 UTC
Labels: duplicate
