### ISSUE TITLE
When I start Spotify it stays on this black screen

### ISSUE THREAD

**Issue by JxseDelRey** [surfbryce/beautiful-lyrics#347] opened 2024-04-04 19:45 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/153209219/0dbd7f10-1490-4016-8575-ef582f308331)

**Comment by surfbryce** [comment] 2024-04-05 05:33
Duplicate of #340

**Closed by surfbryce** 2024-04-05 05:33 UTC
Labels: duplicate
