### ISSUE TITLE
Beautiful Lyrics bugs out lyrics pane and isn't working in the sidebar

### ISSUE THREAD

**Issue by aamyush** [surfbryce/beautiful-lyrics#96] opened 2023-08-05 05:16 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/107539318/2c1a4596-f5f8-49ea-97c0-0bca69425d12)

**Comment by aamyush** [comment] 2023-08-05 05:17
SS from version 3.1.10 after updating from 3.1.8 with the same bug

**Comment by aamyush** [comment] 2023-08-05 05:19
![image](https://github.com/surfbryce/beautiful-lyrics/assets/107539318/d318cd7b-c2bb-48d1-a716-4e8ebf5471ca)

**Comment by surfbryce** [comment] 2023-08-05 05:19
@aamyush You need to be more specific. I'm not sure what you mean at all by the title.

What is "BF"? Can you open up the console - to do that run the command "spicetify apply enable-devtools" and then right click on any open space and open "Developer Tools" - finally, click the Console tab and screenshot everything there.

And has it been like before the recent updates? What theme are you using (if any)?

**Comment by aamyush** [comment] 2023-08-05 05:21
> @aamyush You need to be more specific. I'm not sure what you mean at all by the title.
> 
> What is "BF"? Can you open up the console - to do that run the command "spicetify apply enable-devtools" and then right click on any open space and open "Developer Tools" - finally, click the Console tab and screenshot everything there.
> 
> And has it been like before the recent updates? What theme are you using (if any)?

"bf" as in beatiful lyrics, wait can you not see the attached imaged?

**Comment by aamyush** [comment] 2023-08-05 05:23
> @aamyush You need to be more specific. I'm not sure what you mean at all by the title.
> 
> What is "BF"? Can you open up the console - to do that run the command "spicetify apply enable-devtools" and then right click on any open space and open "Developer Tools" - finally, click the Console tab and screenshot everything there.
> 
> And has it been like before the recent updates? What theme are you using (if any)?

it just started happening recently on 3.1.8, updated to 3.1.10 and still doesn't work, let me try attaching the dev tools screenshots

**Comment by surfbryce** [comment] 2023-08-05 05:23
@aamyush I can see the attached image; however, like I said in my previous comment - I can't do much without seeing the console.

This issue doesn't happen for everyone and hasn't happened for me. So it leads me to believe that it's an operating system or Spotify issue.

**Comment by aamyush** [comment] 2023-08-05 05:24
> spicetify apply enable-devtools

![image](https://github.com/surfbryce/beautiful-lyrics/assets/107539318/3605a252-5dd7-437d-9090-1db691481a66)

**Comment by aamyush** [comment] 2023-08-05 05:25
![image](https://github.com/surfbryce/beautiful-lyrics/assets/107539318/fac2bbcd-7ecb-4652-9b80-29aa335a273c)

**Comment by surfbryce** [comment] 2023-08-05 05:28
@aamyush Can you include the entire console, warnings and errors. It'll help me out since not everything is always an error

**Comment by aamyush** [comment] 2023-08-05 05:29
i am not using any themes :) I love this extension, Its my favorite extension so yes i'll do anything, how can i include the entire console?

**Comment by surfbryce** [comment] 2023-08-05 05:30
@aamyush What I meant was just screenshot everything you see there. Not just the errors

**Comment by aamyush** [comment] 2023-08-05 05:34
![image](https://github.com/surfbryce/beautiful-lyrics/assets/107539318/9769782a-1783-4571-9b45-4c50a5d8210d)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/107539318/3401e0b6-2090-483e-bb5c-3e2576e2d956)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/107539318/f39bd816-97a1-4578-9ff2-db45bec8a8bf)
This is everything that i can see on the devtools window!

**Comment by aamyush** [comment] 2023-08-05 05:38
![image](https://github.com/surfbryce/beautiful-lyrics/assets/107539318/9929189c-ec88-4e09-b76b-1e8e2386a9ad)
i dont know how any of this works or what i am looking at, but it shows this too

**Comment by surfbryce** [comment] 2023-08-05 05:50
@aamyush I'm assuming the issue is with this:
<img width="1584" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/81ea24ac-d8fc-4678-8119-f3e569a2f4ec">

Uninstall the extension. Restart Spotify. Then re-install the extension. It should work after that. This issue was fixed in a recent bug-fix

**Comment by aamyush** [comment] 2023-08-05 05:53
@surfbryce just tried exactly that the extension still seems to be non functional, also i saw another issue opened with the same bug

**Comment by surfbryce** [comment] 2023-08-05 05:54
@aamyush Yeah but their situation (at least for one of them) is a little different, you can see the updated progress on that bug.

**Comment by aamyush** [comment] 2023-08-05 05:56
i dont lknow if this helps or not but the lyrics pane looks like this with the extension installed
![image](https://github.com/surfbryce/beautiful-lyrics/assets/107539318/4770bb7a-a551-4fba-b2d2-c1fd61b19a51)
and like this without the extension
![image](https://github.com/surfbryce/beautiful-lyrics/assets/107539318/719e4203-1215-49b4-a1d6-4e55abd16f69)

**Comment by aamyush** [comment] 2023-08-05 05:57
> @aamyush Yeah but their situation (at least for one of them) is a little different, you can see the updated progress on that bug.
> 
> You'll have to wait until the content network that Spicetify uses to give people the extension code updates. Since I think this is primarily an issue with one of the older versions still being used by it and it breaking the new version.
> 
> This might not happen until tomorrow or in a couple hours.
> 
> I apologize for the issue, but from what we have to work with here there's nothing I can do.

oh no need to apologize at all, in-fact, thank YOU for a great extension, worked flawlessly till just now and am sure it'll be fixed!

**Comment by surfbryce** [comment] 2023-08-05 06:10
@aamyush I appreciate the understanding. I'll keep this issue and will keep an eye out on it - you should *hopefully* see this fixed either by tomorrow or in a couple of hours (when the content stuff gets updated on Spicetifys side)

**Comment by newBonfire** [comment] 2023-08-05 08:05
I'm facing the same issue on linux. the lyrics on the right sidebar doesn't work.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/97826978/ec69a126-94ee-4024-a2a3-b53769b9088d)

It works fine when I go to lyrics page.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/97826978/40a3dd4f-7977-4414-853b-33c348e22f46)

**Comment by surfbryce** [comment] 2023-08-06 09:20
@aamyush @newBonfire Alright so I'm going to close this, mark it as a duplicate, and move everyone who has this issue to #89. The super simple reason for this is because I think I just found out why lots of people are having this issue. I'll post my theory over there.

**Closed by surfbryce** 2023-08-06 09:20 UTC
