### ISSUE TITLE
Background changes

### ISSUE THREAD

**Issue by franchecco** [surfbryce/beautiful-lyrics#899] opened 2024-09-20 15:54 UTC
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

could you make it possible to change the background? I have not a powerful computer and when i use beautiful lyrics the GPU start .
If it's possibile deactivate the dynamic background for a static one and the glowing text for a normal one.
Thanks

### What is your Suggestion?

I don't know like a switch for a eco-mode or something else

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment] 2024-09-22 01:05
@franchecco Duplicate of #157

**Closed by surfbryce** 2024-09-22 01:05 UTC
Labels: Duplicate, Suggestion
