### ISSUE TITLE
The full page lyric sync is not working

### ISSUE THREAD

**Issue by harnidhskhera** [surfbryce/beautiful-lyrics#364] opened 2024-04-07 06:38 UTC
When the lyrics page is opened the page is black
![image](https://github.com/surfbryce/beautiful-lyrics/assets/89342170/71e74a14-2f7f-42e1-aa82-9f5c186d6f8b)

**Comment by jaboosky** [comment] 2024-04-07 06:47
[This is already an Issue.](https://github.com/surfbryce/beautiful-lyrics/issues/340)

**Comment by harnidhskhera** [comment] 2024-04-07 08:54
I see, is there any solution to this issue?

**Comment by 209726742** [comment] 2024-04-07 09:57
"Why does your Spotify look like that? Did you guys use a theme or something?"
![Uploading 微信截图_20240407175717.png…]()

**Comment by 209726742** [comment] 2024-04-07 09:58
Why does your Spotify look like that? Did you guys use a theme or something?
![微信截图_20240407175717](https://github.com/surfbryce/beautiful-lyrics/assets/54384262/92370e25-a394-40e8-9aa2-913e508af44e)

**Comment by 209726742** [comment] 2024-04-07 10:06
“Made for you”    you can find it in the extensions     
<img width="171" alt="1712484363393" src="https://github.com/surfbryce/beautiful-lyrics/assets/54384262/a917f4da-5810-4fb7-985d-39a1eeb2bc9a">

**Comment by surfbryce** [comment] 2024-04-07 16:16
Duplicate of #340

**Closed by surfbryce** 2024-04-07 16:16 UTC
Labels: duplicate
