### ISSUE TITLE
Lyrics page can't be seen

### ISSUE THREAD

**Issue by SirrFloppy** [surfbryce/beautiful-lyrics#466] opened 2024-05-05 10:51 UTC
when i click on lyrics page it doesn't appear 
![image_2024-05-05_115123920](https://github.com/surfbryce/beautiful-lyrics/assets/168966486/82c33b68-46ad-44ab-8f08-e12f19acf356)

**Comment by DeadRisingStar** [comment] 2024-05-05 11:33
Pretty sure its cause Spotify put lyrics behind a paywall today.

**Comment by Joemama069420** [comment] 2024-05-05 11:38
same
![Screenshot 2024-05-05 170828](https://github.com/surfbryce/beautiful-lyrics/assets/152177661/df70c6bb-df15-4dd1-bd0c-16485cbd3489)

**Comment by surfbryce** [comment] 2024-05-05 18:16
Duplicate of #441, and no @DeadRisingStar it's not because Spotify put lyrics behind a paywall, it was cause by a Spotify update a few months ago, Spotify paywall will not affect Beautiful Lyrics

**Closed** 2024-05-05 18:16 UTC
Labels: duplicate
