### ISSUE TITLE
The lyrics disappear

### ISSUE THREAD

**Issue by StormyCalmar** [surfbryce/beautiful-lyrics#453] opened 2024-05-01 15:50 UTC
When I try to put the lyrics in full screen it doesn't work and the dynamic theme is disabled. (My theme is flow)

https://github.com/surfbryce/beautiful-lyrics/assets/168660353/334d35d7-913b-43df-9022-3c02b018d179

**Comment by surfbryce** [comment] 2024-05-01 17:29
Duplicate of #441

**Closed by surfbryce** 2024-05-01 17:29 UTC
Labels: duplicate
