### ISSUE TITLE
Summarize the Bug/Issue Here

### ISSUE THREAD

**Issue by Guicsr2** [surfbryce/beautiful-lyrics#841] opened 2024-08-15 20:33 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

![SCR-20240815-pjay](https://github.com/user-attachments/assets/39f378e4-d051-4252-815d-7ee9b9653880)

### What Country are you from?

Brazil

### What Operating System are you using?

MacOS

### Spotify/Spicetify Information

Spotify para macOS (Apple Silicon)
1.2.44.405.g81d6352
• Spicetify v2.37.1

### Spotify HTML/CSS and Console Screenshots

<img width="423" alt="image" src="https://github.com/user-attachments/assets/cbf88538-8003-4a96-b7fc-9651f36b4d54">

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment] 2024-08-17 20:48
@Guicsr2 This is a duplicate of #838

**Closed by surfbryce** 2024-08-17 20:48 UTC
Labels: Extension Bug, Duplicate

**Comment by Guicsr2** [comment] 2024-08-17 21:01
Ow Right, I find The way to fix this, in this post #838 using a CSS code, thanks.
