### ISSUE TITLE
Hungarian lyrics gets converted into RTL layout

### ISSUE THREAD

**Issue by IrepY** [surfbryce/beautiful-lyrics#52] opened 2023-07-02 21:18 UTC
Title says it all, Hungarian is not an RTL language, however it gets converted, just like on the screenshot. 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/82579394/a1a0274a-2de8-42a0-a281-19af70608706)

**Comment by surfbryce** [comment] 2023-07-02 21:20
I'll mark this as a duplicate of #50 and just rename that - there should be an update today to fix this; thanks for the additional scenario - could you also provide the name of song?

**Closed by surfbryce** 2023-07-02 21:20 UTC
Labels: duplicate
