### ISSUE TITLE
Full Screen Mode hiding more lanes.

### ISSUE THREAD

**Issue by iJAJAxD** [surfbryce/beautiful-lyrics#683] opened 2024-06-01 06:12 UTC
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

Lots of lanes are seen from the music. As seen in the image, I can see about 5 - 6 lanes of lanes without it playing.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/141394554/eba71afb-94bd-476e-9c25-c5d40608b5be)

### What is your Suggestion?

Try to hide the lyrics more when they are not in the part where they are played. For example, in the image I can see 6 lines of lyrics. I suggest taking the idea of lyrics-plus or Apple Music, which displays 1 or 2 lanes and blurring the next one. Example below:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/141394554/af4a5824-633e-49d7-ab60-9f209be2f5fe) 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/141394554/e034ddae-57c9-44b8-8101-ca090a5ce18f)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment] 2024-06-03 20:48
Duplicate of #606

**Closed by surfbryce** 2024-06-03 20:48 UTC
Labels: Duplicate, Suggestion
