### ISSUE TITLE
Theme Hazy Issues

### ISSUE THREAD

**Issue by brokenkie** [surfbryce/beautiful-lyrics#455] opened 2024-05-02 01:11 UTC
Hey - just wanted to flag that the Hazy theme seems to maken the lyrics disappear. 

Hazy, Spicetify, and Spotify have all been freshly reinstalled.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/34959512/4c7006c1-8a32-4338-befc-d1ad5f02ebf8)

**Comment by surfbryce** [comment] 2024-05-02 01:12
Duplicate of #441

**Closed by surfbryce** 2024-05-02 01:12 UTC
Labels: duplicate
