### ISSUE TITLE
Suggestion: Theme with the wobbly background and the nice bloom

### ISSUE THREAD

**Issue by fxyqq** [surfbryce/beautiful-lyrics#121] opened 2023-08-21 14:15 UTC
Would be nice to have a theme with the wobbly background and a nice bloom and font!

![image](https://github.com/surfbryce/beautiful-lyrics/assets/75327915/6e5380f5-b593-4fbf-a207-7444e799d310)

the pink background matches the song so that with full spotify background and theme!

**Comment by surfbryce** [comment] 2023-08-21 23:58
This is a duplicate of #37

**Closed by surfbryce** 2023-08-21 23:58 UTC
Labels: duplicate
