### ISSUE TITLE
Add compact lyrics view in cinema mode

### ISSUE THREAD

**Issue by agent255** [surfbryce/beautiful-lyrics#695] opened 2024-06-04 13:18 UTC
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

Like in Full App Display, compact lyrics don't show all the lyrics at once but only 4 lines. Having something like this in cinema mode would be rlly good

### What is your Suggestion?

![image](https://github.com/surfbryce/beautiful-lyrics/assets/70315828/0be96e4b-196f-4663-b8f6-5aef2dac1c63)
Full lyrics
![image](https://github.com/surfbryce/beautiful-lyrics/assets/70315828/b44811df-188d-4636-91ca-2f43288447b6)
compact lyrics

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment] 2024-06-04 19:24
@agent255 Duplicate of #606

**Closed by surfbryce** 2024-06-04 19:24 UTC
Labels: Duplicate, Suggestion

**Comment by agent255** [comment] 2024-06-05 10:52
sorry i only searched for compact lyrics in issues
