### ISSUE TITLE
the song cover dosent fit to frame

### ISSUE THREAD

**Issue by fergie5675** [surfbryce/beautiful-lyrics#962] opened 2024-11-02 19:05 UTC
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

![Screenshot 2024-11-02 190346](https://github.com/user-attachments/assets/d1319756-34df-499b-af24-96348c2d1e8a)

its not fit to frame

### What Country are you from?

United States

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

d

### Spotify HTML/CSS and Console Screenshots

![Screenshot 2024-11-02 190346](https://github.com/user-attachments/assets/39d17397-87c4-4e8c-9be6-e12782b9a326)

### Information Checklist

- [ ] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Stormygood** [comment] 2024-11-03 16:03
Guess this problem became recent, huh? I'm having the same treatment from the extension.

**Comment by Mysticc28** [comment] 2024-11-03 17:15
Hello there, there's a quick fix for the misoriented elements in the Beautiful Lyrics extension available thanks to @sanoojes

**Step 1 - Copy the below code** 
```typescript
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
    position: relative;
}
``` 
**Step 2 - Navigate to Spotify>Marketplace>Snippets**
![image](https://github.com/user-attachments/assets/2decf258-2f0e-4e65-985e-d5f2ac483a8b)

**Step 3 - Click the 'Add CSS' button in the bottom right corner**
![image](https://github.com/user-attachments/assets/3c156d43-7c5b-4956-8f97-ae4794aae606)

**Step 4 - Under Custom CSS, paste the code you just copied and add a Snippet name and description as you wish. Should look something like this so far.** 
![image](https://github.com/user-attachments/assets/9e29e9b9-4293-418e-8db7-a9d97c425a28)

**Step 5 - Hit Save CSS and done.** 
Your issue should be fixed but incase it isnt, refresh Spotify and check again. Once again, a big thanks to @sanoojes for the fix. Check out his themes, they're really cool. 

@fergie5675 @Stormygood here's the fix y'all

**Comment by sanoojes** [comment] 2024-11-03 22:46
Duplicate of https://github.com/surfbryce/beautiful-lyrics/issues/954

**Comment by Stormygood** [comment] 2024-11-04 06:43
Holy shit man. Thanks. Sorry for duplicating the problem. 😅

**Closed** 2024-11-15 22:05 UTC
Labels: Extension Bug
