### ISSUE TITLE
Add to liked songs button misplaced in full screen

### ISSUE THREAD

**Issue by Auckshay** [surfbryce/beautiful-lyrics#344] opened 2024-04-04 02:17 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/153153175/7ad63ac7-1ae8-4440-9d90-cec2bc1c5218)
when going into full screen mode the add to liked song button is misplaced

**Comment by surfbryce** [comment] 2024-04-04 02:56
Duplicate of #231

**Closed by surfbryce** 2024-04-04 02:56 UTC
Labels: duplicate
