### ISSUE TITLE
Using a lot of cpu.

### ISSUE THREAD

**Issue by DewDropTales** [surfbryce/beautiful-lyrics#565] opened 2024-05-18 18:54 UTC
So I haven't seen any other issue been submitted about this but in my spotify the seccond I open the beautiful lyrics page my cpu usage spikes to 40-46% and in the official its between 1.8-8%. please help me fix this.
![Taskmgr_7zBfjClzZt](https://github.com/surfbryce/beautiful-lyrics/assets/100445832/a22b43f6-4caa-455b-8b11-fda0c7e8907c)
![Taskmgr_OdM8TNsHkt](https://github.com/surfbryce/beautiful-lyrics/assets/100445832/5d91b051-65a5-4cac-9587-5f6c43a37197)

**Comment by sqmbutbetter** [comment] 2024-05-18 20:13
This is happening to me too on even the latest version of spotify. my pc is low end which means even if im not using the lyrics my spotify is too laggy to use while having the extension installed, very sad that I cannot use it right now due to this.

**Comment by surfbryce** [comment] 2024-05-18 21:24
Duplicate of an already existing issue

**Closed by surfbryce** 2024-05-18 21:24 UTC
Labels: duplicate
