### ISSUE TITLE
last update broke everything

### ISSUE THREAD

**Issue by thecaprisun** [surfbryce/beautiful-lyrics#562] opened 2024-05-18 11:40 UTC
![image](https://github.com/surfbryce/beautiful-lyrics/assets/156376854/f6cd25ae-f483-42e4-8b33-df3c33c14fd9)
yeah it's unusable, i need to use another device just to change music

**Comment by garryspins** [comment] 2024-05-18 12:05
![this](https://i.imgur.com/GhgMeyJ.png) Closing the sidepanel fixes it temporarily

**Comment by thecaprisun** [comment] 2024-05-18 14:07
> ![this](https://camo.githubusercontent.com/7cd626fd939d9b72077dbfb25e879c01206e5c14526aebdfa4b3cda21e72d404/68747470733a2f2f692e696d6775722e636f6d2f4768674d65794a2e706e67) Closing the sidepanel fixes it temporarily

ah ok, thx
ig i'll just disable the extension until it'll be fixed

**Comment by vilewired** [comment] 2024-05-18 15:53
check #541

**Comment by surfbryce** [comment] 2024-05-18 21:28
Duplicate of #541

**Closed by surfbryce** 2024-05-18 21:28 UTC
Labels: duplicate

**Comment by Monoverde888** [comment] 2024-05-18 23:42
duplicate of a duplicate?? why don't you just mention the first one
