### ISSUE TITLE
The "add to playlist" button is so annoying in the full screen mode

### ISSUE THREAD

**Issue by ICExHUNTER** [surfbryce/beautiful-lyrics#309] opened 2024-03-02 11:48 UTC
![Screenshot 2024-03-02 134523](https://github.com/surfbryce/beautiful-lyrics/assets/153937504/1b0b0972-a864-4682-8c33-5856675e6474)

**Comment by surfbryce** [comment] 2024-03-02 11:49
Duplicate of #231

**Closed by surfbryce** 2024-03-02 11:49 UTC
Labels: duplicate
